### ISSUE TITLE
[BUG ANDROID] java.lang.IllegalStateException: sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by Nico3652** [SimformSolutionsPvtLtd/audio_waveforms#105]
When I'm using the stop method from the player on Android I have a Handler issue :

```
W/MessageQueue(30845): Handler (android.os.Handler) {e8b7c24} sending message to a Handler on a dead thread
W/MessageQueue(30845): java.lang.IllegalStateException: Handler (android.os.Handler) {e8b7c24} sending message to a Handler on a dead thread
W/MessageQueue(30845): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:567)
W/MessageQueue(30845): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(30845): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(30845): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(30845): 	at android.os.Handler.sendMessage(Handler.java:635)
W/MessageQueue(30845): 	at android.os.Message.sendToTarget(Message.java:469)
W/MessageQueue(30845): 	at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
W/MessageQueue(30845): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.stop(ExoPlayerImplInternal.java:334)
W/MessageQueue(30845): 	at com.google.android.exoplayer2.ExoPlayerImpl.stopInternal(ExoPlayerImpl.java:1702)
W/MessageQueue(30845): 	at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:933)
W/MessageQueue(30845): 	at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:926)
W/MessageQueue(30845): 	at com.simform.audio_waveforms.AudioPlayer.stop(AudioPlayer.kt:127)
W/MessageQueue(30845): 	at com.simform.audio_waveforms.AudioWaveformsPlugin.onMethodCall(AudioWaveformsPlugin.kt:94)
W/MessageQueue(30845): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/MessageQueue(30845): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/MessageQueue(30845): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/MessageQueue(30845): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/MessageQueue(30845): 	at android.os.Handler.handleCallback(Handler.java:938)
W/MessageQueue(30845): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/MessageQueue(30845): 	at android.os.Looper.loop(Looper.java:250)
W/MessageQueue(30845): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
W/MessageQueue(30845): 	at java.lang.reflect.Method.invoke(Native Method)
W/MessageQueue(30845): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/MessageQueue(30845): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

When calling : 

```
await playerController.stopPlayer();
```

This is not 100% reproductible and unfortunately I can't provide more info on the situation.
This is a very classic use case, It's called on dispose() after playing audio in the main page.

Device : Motorola on Android 11

Thanks

**Comment by Ujas-Majithiya** [comment]
Hey @Nico3652, 
Look at the error you are getting  `sending message to a Handler on a dead thread`, it means that you are trying to use  native resources which are already disposed, in your case you are stopping the player inside dispose method as it's an `async` call it will take time and while stopPlayer is running screen will be already disposed. And it's sometimes reproduceable is maybe due to sometimes stopPlayer getting completed early before the screen is disposed.

It's same as you try to use any other flutter controllers like AnimationController or ScrollController after screen is disposed. If you use them after screen is disposed you will get error. 

So here only dispose the screen after `stopPlayer` is completed.

**Comment by Nico3652** [comment]
Hi @Ujas-Majithiya

In my case it will be more complicated then because I have a "swipe back" closing gesture, so the initial pop -> dispose is called without trigger from my code. 

I only did this for swipe handling 

```
@override
  void dispose() {
    player.stopPlayer();
    super.dispose();
  }
```

As far as I know we can't delay / await in dispose method and other ```AnimationController```  allow to call ```controller.dispose()``` without async so there are no problem on swipe back. 

I also have a back button in addition to the swipe, which I have fixed with your info by waiting the player, before call ```Navigator.pop(context)```

Anyway I can close this because this is on my part now thanks for explanations
