### ISSUE TITLE
iOS fails to record

### ISSUE THREAD

**Issue by 3ph** [SimformSolutionsPvtLtd/audio_waveforms#107]
Recording on the device doesn't work - a file is created but has zero length. There is no error for the recording part - no waves are being shown while recording (only dots). I have tried to debug iOS code but there doesn't seem to be any error - `getDecibels` always return -120.

I have tried on 2 iOS devices (iOS14, iOS16), both behaving the same. Permissions to microphone are granted.

The code follows the example (simplified version):
```
@override
void initState() {
    super.initState();
    recorderController = RecorderController();
    playerController = PlayerController();
  }
...

onPressed: () async {
  await recorderController.record();
},

...

nPressed: () async {
  var path = await recorderController.stop();
  debugPrint(path);
  await playerController.preparePlayer(path!); // <-- this will fail (I assume) because the file is empty
}

...

AudioWaveforms(
  size: Size(MediaQuery.of(context).size.width, 10.0),
  recorderController: recorderController,
  waveStyle: const WaveStyle(
  showMiddleLine: false,
),
```

**Comment by ujas-m-simformsolutions** [comment]
Hey @3ph can you please try changing sampleRate to 44100 and bitRate to 48000

**Comment by 3ph** [comment]
Hey @ujas-m-simformsolutions, great suggestion, it works now, thanks a lot. Wouldn't it make sense to make these defaults? Or maybe mention it in the readme?
Great job on the package anyway!

**Comment by ujas-m-simformsolutions** [comment]
@3ph there is one PR that changes these default values.
