### ISSUE TITLE
The Android music wave is inverted

### ISSUE THREAD

**Issue by csacchetti** [SimformSolutionsPvtLtd/audio_waveforms#108]
I have a strange problem. While iOS shows the music wave correctly with the silence spaces at zero, Android seems to show it inverted, in fact right from the start, when I haven't started talking yet it is at maximum and if I start talking it drops proportionally.
I don't understand if I have done something wrong (but I use your example) or there is a real problem.
Any suggestion?

**Comment by csacchetti** [comment]
I use normalizationFactor to obtain a good wave also in android

**Comment by jackwill99** [comment]
Are you ok recording in iOS?? I also use this repo example but iOS can't record. If you are ok, can you share your code for iOS?

**Comment by ujas-m-simformsolutions** [comment]
@jackwill99 Check [this](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/107#issuecomment-1258973451) out. And closing this since the issue is been resolved.

**Comment by guoz2013** [comment]
How do you resolved the problem?

**Comment by csacchetti** [comment]
I use normalizationFactor to obtain a good wave also in android
