### ISSUE TITLE
waves that are not displayed

### ISSUE THREAD

**Issue by tchapdev** [SimformSolutionsPvtLtd/audio_waveforms#111]
Hi there, I can't display the waves of my audio files, and when I display on the console the result of `playerController.bufferData`, I get the `null `response, so how to solve this please

**Comment by tchapdev** [comment]
problem solved

**Comment by digrowfa** [comment]
can you please explain how you solved it ? i am facing the same issue

**Comment by digrowfa** [comment]
> problem solved

please take a look above

**Comment by deevsaini** [comment]
can you please tell me how you solve it ? I am facing the same issue!

> problem solved
