### ISSUE TITLE
Not showing waves for first 2-4 seconds.

### ISSUE THREAD

**Issue by N-sravan** [SimformSolutionsPvtLtd/audio_waveforms#115]
Not showing waves for first 2-4 seconds in IOS recorded file. In Android it's working fine.

**Comment by ujas-m-simformsolutions** [comment]
Please share your implementation so that we can check where is the issue.

**Comment by ujas-m-simformsolutions** [comment]
We have release 1.0.0 which may fix this issue. I'm closing this issue for now but if issue persist feel free to open a new issue
