### ISSUE TITLE
 Microphone might be turned off

### ISSUE THREAD

**Issue by NafissaBHJ** [SimformSolutionsPvtLtd/audio_waveforms#119]
I'm having a message that says " D/AudioWaveforms( 1299): Microphone might be turned off " when I start recording when I have already gave access to Microhphone in the manifest file .

**Comment by ujas-m-simformsolutions** [comment]
Duplicate of https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/73. Check https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/73#issuecomment-1200409384 comment to enable the microphone for the android emulator.

**Comment by NafissaBHJ** [comment]
But I'm using a real device and not an emulator.

**Comment by ujas-m-simformsolutions** [comment]
@NafissaBHJ This warning only comes when reported decibels are `Double.NEGATIVE_INFINITY` on the android side. This happens only for android emulators and this should happen for real devices. Are you using default config for this?

**Comment by NafissaBHJ** [comment]
Which  default config ?
