### ISSUE TITLE
Audio Waveforms doesn't read the initial value of the controller at first

### ISSUE THREAD

**Issue by Aneess333** [SimformSolutionsPvtLtd/audio_waveforms#120]
Let's suppose you have a player controller and your player controller current duration is 5 sec but in the waveform it will show no active waves. When we play the audio then it reads the current controller current duration then it seek to that position and play it from there. the main issue is with initial display of waves.

**Comment by Aneess333** [comment]
It creates an issue in list view. I am using list view and inside it there are audios.. but there is an option to record and add new audio.. So let's suppose you play and audio and stop it in center and then record a new audio and send it then after sorting it is taking 0 index in list.. so at the 0 index it is showing previous 0 index position in waveform although it have new controller.. so when I play this then it will play correct audio but at first the issue is with display of waveforms at first. This can be solved if you read the controller current duration and update the active waveforms. Thank you

**Comment by ujas-m-simformsolutions** [comment]
@Aneess333 sorry for late reply, If you can provide reproducible code then we might able to help you with this.

**Comment by ujas-m-simformsolutions** [comment]
As no response was provided I'm going to close this issue.
