### ISSUE TITLE
When I pause and play the audio player, the wave is shown not correctly.

### ISSUE THREAD

**Issue by kido-luci** [SimformSolutionsPvtLtd/audio_waveforms#121]
https://user-images.githubusercontent.com/41099231/198017627-11dc5e48-0ac0-4ee3-85e4-a87a59132aa6.mp4

**Comment by ujas-m-simformsolutions** [comment]
We have 2 PRs pending which might fix this issue.

**Comment by ujas-m-simformsolutions** [comment]
We have release 1.0.0 which may fix this issue. I'm closing this issue for now but if issue persist feel free to open a new issue
