### ISSUE TITLE
Error loading audio file

### ISSUE THREAD

**Issue by Klinsman21** [SimformSolutionsPvtLtd/audio_waveforms#122]
<img width="1139" alt="Captura de Tela 2022-11-01 às 22 04 12" src="https://user-images.githubusercontent.com/32601062/199370580-02754906-b180-4da5-9115-0ed990711e7b.png">

**Comment by gideonoyekale** [comment]
Facing the same issue

**Comment by ujas-m-simformsolutions** [comment]
@Klinsman21 I see you have space in your name of the audio file, try removing the space.

**Comment by viandmarket25** [comment]
hello, could you check this out?

From my investigation, this char "%" should not be in the file name, my file result is:
 file:///private/var/mobile/Containers/Data/Application/82AE8E02-9502-496D-8BB1-253F1D16D196/tmp/22-12-04-10-46-09%20PM.aac


but I was expecting something like this:

File: '/var/mobile/Containers/Data/Application/82AE8E02-9502-496D-8BB1-253F1D16D196/Library/Caches/31099c70-73e2-11ed-8e9d-39cdd676bc8e.m4a'

I removed the "%" but no luck, could you take a look at the File result?

**Comment by ujas-m-simformsolutions** [comment]
I have made some changes in #142. We will see if this fixes this issue.

**Comment by ujas-m-simformsolutions** [comment]
From 1.0.1 release it should be fixed but if issue persist please do file a new issue.
