### ISSUE TITLE
 The wave effect does not move with the sound.

### ISSUE THREAD

**Issue by emrhnzngn** [SimformSolutionsPvtLtd/audio_waveforms#124]
The wave effect does not move with the sound. Help?

**Comment by enamulhaque028** [comment]
I also faced the same issue both in android and iOS.

**Comment by elvisgn** [comment]
Having the same issue. On the last version of flutter (3.3.8) and audio_waveforms package (0.1.5+1).

The audio is complete and the progress bar is in sync with the recording, but the visualization is wrong.

**Comment by ujas-m-simformsolutions** [comment]
There are 2 open PRs #126 #123  which might fix the sync issue and wrong visualization.
