### ISSUE TITLE
Delete voice message

### ISSUE THREAD

**Issue by Sarat-1997** [SimformSolutionsPvtLtd/audio_waveforms#128]
I had refered your code and it was very nice and clear but little doubt when we send a voice message in which it is not clear and how can we delete it?

**Comment by ujas-m-simformsolutions** [comment]
This isn't in the scope of the this plugin but you can use this,
```
Future<void> deleteFile(File file) async {
  try {
    if (await file.exists()) {
      await file.delete();
    }
  } catch (e) {
    // Error in getting access to the file.
  }
}
```

**Comment by Sarat-1997** [comment]
Thank you very much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
