### ISSUE TITLE
Fitwidth rendering strange behavior

### ISSUE THREAD

**Issue by Nico3652** [SimformSolutionsPvtLtd/audio_waveforms#143]
Hi @ujas-m-simformsolutions and thanks for this new release which is solving almost all our issues. 

However I'm facing a strange behavior while using the ```fitWidth``` concept because this is not the same on Android & iOS. 
I don't know yet if this is a bug, but it could be a question.

On iOS, i have to set ```continuousWaveform``` to true to make it work, and set to false on Android :

If I'm setting true on Android, during the build, there is a flicker of the drawing on screen and then the fitwidth is ignored few milliseconds later and render the .long 

Here is the widget inside the build : 
```
widget.controller.waveWidth == 0 && widget.controller.waveformData.isNotEmpty
                    ? const SizedBox()
                    : AudioFileWaveforms(
                        size: Size(widget.controller.waveWidth, 80),
                        playerController: widget.controller.player,
                        enableSeekGesture: false,
                        // If continuous is set to true it will not work on android
                        // for drawing wave form
                        continuousWaveform: Platform.isIOS,
                        waveformType: WaveformType.fitWidth,
                        waveformData: widget.controller.waveformData,
                        playerWaveStyle: const PlayerWaveStyle(
                            fixedWaveColor: Colors.grey,
                            liveWaveColor: Colors.white,
                            scaleFactor: 80,
                        ),
                      ),
``` 

I have a model (controller) which is basically calculating the wave width according screen size and audio length,
then notify when ready. The initializing looks like this :

```
      Future<void> initWaves() async {
    waveWidth = audioDurationMillis * availableWidth / totalSelectionMillis;
    waveformData.clear();
    final samples = const PlayerWaveStyle().getSamplesForWidth(waveWidth);
    waveformData = await player.extractWaveformData(path: currentUrl, noOfSamples: samples);
    notifyListeners();
  }
```

I'm using the extract and set directly the data when reloading. 

So as I said, this logic is only working on iOS with ```continuousWaveform``` true and false for Android. Otherwise the fitWidth is ignored and the long is drawn. 

I am missing something for the new config or this is a bug ? 
If this not enough I can share a screen record but I couldn't right now.

Thanks for your help

**Comment by ujas-m-simformsolutions** [comment]
First, you are not supposed to pass `waveformData` by your self when you are extracting and also showing waveform at same time. The widget will automatically take waveformData when extracting from `extractWaveformData` or `preparePlayer(shouldExtractWaveform: true)`. Waveform data should only be passed when you already have full data.

Here, I think what is happening that widget is taking data by itself from the assigned controller's stream and you are also passing same data whenever you get the new data and whole widget gets rebuilt twice. Also I'm not sure about the logic `&& widget.controller.waveformData.isNotEmpty
                    ? const SizedBox()`, shouldn't show waveforms when it is not empty. 
And for `fitWidth` being ignored, we have to check that further but first let's see if above suggestion resolves your issue.

You can take reference from [migration guide](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/migration_guide.md) and also [example app](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/example/lib/chat_bubble.dart). The example app contains showing waveform when extracting from `extractWaveformData` or `preparePlayer`.

**Comment by ujas-m-simformsolutions** [comment]
I just checked the migration guide and I guess the wording is makes it look like user have to directly pass the data to improve performance. I will update it in next release.

**Comment by Nico3652** [comment]
Ok sorry I made (handwriting) mistake in the condition for ```SizedBox()``` but it doesn't matter here (just safety).

> I just checked the migration guide and I guess the wording is makes it look like user have to directly pass the data to improve performance

This is really true. And in my case also though I will make it work in that way. 

So I've tested again according the example, and I fixed my issue using ```shouldExtractWaveForm``` to false in ```preparePlayer``` and then ```extractWaveformData``` with ```getSamplesForWidth(width);``` and removing my own waveformData array in widget.

Here is my solution for both :  

```
void init() {
await _player.preparePlayer(path: url, shouldExtractWaveform: false);
final samples = const PlayerWaveStyle().getSamplesForWidth(waveWidth);
 await player.extractWaveformData(path: currentUrl, noOfSamples: samples);
notifyListeners();
}
```

But on Android the ```preparePlayer``` with ```shouldExtractWaveForm``` true completely ignore the fitWidth : 

```
await _player.preparePlayer(path: url, shouldExtractWaveform: true);
if (_player.playerState != PlayerState.playing) {
      _player.startPlayer(finishMode: FinishMode.loop);
}

........

AudioFileWaveforms(
                        size: Size(widget.controller.waveWidth, 80),
                        playerController: widget.controller.player,
                        enableSeekGesture: false,
                        waveformType: WaveformType.fitWidth,
                        playerWaveStyle: const PlayerWaveStyle(
                            fixedWaveColor: Colors.grey,
                            liveWaveColor: Colors.white,
                            scaleFactor: 80,
                        ),
                   ),
```

This is the same logic I've seen in the sample app for preparePlayer. 

Anyway I was able to fix it so thanks again, I'm letting you close if you have any comment to add for others which may have the same issue.

**Comment by Ujas-Majithiya** [comment]
@Nico3652 you shouldn't use `await` with `extractWaveformData` because if audio file is bigger then it will take some time to extract the data and if use `await` with it then your UI will get stuck for longer times mostly on Android. So if you want the waveform data then prefer using `then` for this function like this.
```
extractWaveformData(...).then((data)=>waveformData = data);
```

**Comment by Nico3652** [comment]
I'm aware about this, I just was waiting for complete in order to notify and reload with this logic, no matter how long it takes.

But anyway I removed my own waveformData now to let the controller do it for me as mentioned above so I don't need to re affect the data
