### ISSUE TITLE
The visualization of the audio being played is slightly delayed to the actual sound 

### ISSUE THREAD

**Issue by dkjazz** [SimformSolutionsPvtLtd/audio_waveforms#145]
And sometimes when the audio ends playing, the visualization gets stuck incomplete (a few bars left un-colored)
![WaveForm](https://user-images.githubusercontent.com/39170109/210262255-fa69cb3d-0bf4-4815-9cd6-51a86a45da01.png)

Here is the style I use in case if it's helpful.

```
  final _audioWaveStyle = const PlayerWaveStyle(
      fixedWaveColor: kPrimaryColor,
      liveWaveColor: kAltPrimaryColor,
      spacing: 3,
      waveCap: StrokeCap.round,
      seekLineThickness: 2,
      waveThickness: 2);
```

and the widget code is

```
AudioFileWaveforms(
              key: ValueKey('AudioFileWaveforms'),
              padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                color: Colors.black12,
              ),
              enableSeekGesture: true,
              waveformType: WaveformType.fitWidth,
              playerWaveStyle: _audioWaveStyle,
              size: _getSizeOfAudioWaveForm(),
              playerController: _playerController,
              waveformData: _waveFormData,
            ),
```

**Comment by ujas-m-simformsolutions** [comment]
As discussed in this issue #143, are you extracting waveform data and providing it widget simultaneously?

**Comment by ujas-m-simformsolutions** [comment]
Now visualization being slightly delayed is because we get current duration update event from native every 200 ms. We can reduce this or provide option to change this but I think a method call less than every 200 ms would very expensive. @dkjazz Do share your thoughts here.

**Comment by dkjazz** [comment]
Ultimately, I don't think it makes sense to expose a new setting to control the update event frequency. From the widget user's point of view the default should just work out of box without getting much into the technical details. I think either:
1. Tune the delay value to balance between visualization and performance (e.g. 100ms or 150ms)
2. Incorporate the delay into the visualization logic, e.g. apply the delay factor to speed up and smooth the visualization.

**Comment by Ujas-Majithiya** [comment]
@dkjazz I'm thinking of providing a n enum for this something like high, medium, low so that user doesn't have to think about this and they can target also target devices with less resources. What do you think about this?

**Comment by ujas-m-simformsolutions** [comment]
Added `updateFrequency` parameter in 1.0.4 releaaw
