### ISSUE TITLE
Audio doesn't play on iPhone in silent mode

### ISSUE THREAD

**Issue by coryswainston** [SimformSolutionsPvtLtd/audio_waveforms#153]
**Describe the bug**
If the silent mode switch is turned on on iPhone, the audio doesn't play. It seems to be playing as a device sound rather than music, etc.

**To Reproduce**
Use a PlayerController and AudioFileWaveforms to play an audio file on an iPhone. No audio is played. This bug does not show up on the simulator.

**Expected behavior**
Audio should be played even in silent mode, just like a music app or audio from the browser.

**Smartphone (please complete the following information):**
Have tested on iPhone 12 and iPhone 13 on latest iOS

**Comment by coryswainston** [comment]
For anyone else with this problem, the [audio_session](https://pub.dev/packages/audio_session) package allows you to designate how audio should be played and solve this problem. Other audio packages have parameters for this so an additional package is not necessary.

**Comment by ujas-m-simformsolutions** [comment]
@coryswainston Thank you for raising this issue. Yes, we observed the same behaviour and found a solution same as you mentioned. Yet this package is more focused on waveforms than the managing audio focus, so we do not have a plan for adding this to the package. Also I think #112 can also be resolved by this.

**Comment by ujas-m-simformsolutions** [comment]
I'm going to close this as unplanned but if you have more suggestions on this then we can discuss more on this.

**Comment by ujas-m-simformsolutions** [comment]
Pinning this issue so that others can find this easily.

**Comment by ujas-m-simformsolutions** [comment]
@venkatd you can fix this by using `audio_session` package. Check its docs to set correct session

**Comment by skirkyn** [comment]
@TNelen hey, did you just change the file extension or also changed the codec?
