### ISSUE TITLE
Ios wave not show in case if not from recordcontroller

### ISSUE THREAD

**Issue by AimanKyo97** [SimformSolutionsPvtLtd/audio_waveforms#155]
I have issue with ios integration, I see @ujas-m-simformsolutions  add sample rate to 44100 and bitrate to 48000 but that if have recordcontroller and its working if in that case, but in my case i want to view only which already got save record file...i cannot view the wave, please help.

@ujas-m-simformsolutions

**Comment by ujas-m-simformsolutions** [comment]
Hey @AimanKyo97, previously we were suggesting to set bitrate but then we found out that setting bitrate will cause file not to be playable on different platform so I suggest remove the bitrate parameter only set it if you are sure that it will work with provided extension and also on all platform.

**Comment by AimanKyo97** [comment]
@ujas-m-simformsolutions , I set bitrate and sample rate and it will work for case that i need record and view it in ios, but the other page i need just view it with no record, i cannot view it which logs say "Exception: Please provide a valid file path"

**Comment by AimanKyo97** [comment]
@ujas-m-simformsolutions i was using version 0.1.4, but once i change to 1.0.1 i got error which say "Error: The getter 'bufferData' isn't defined for the class 'PlayerController'"

**Comment by ujas-m-simformsolutions** [comment]
@AimanKyo97 yes 1.0.0 had some breaking changes, I would recommend checking out the [migration guide](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/migration_guide.md) and [example app](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/example/lib/main.dart).
