### ISSUE TITLE
audioplayer.preparePlayer stops working / Reset Audio 

### ISSUE THREAD

**Issue by HenrikH96** [SimformSolutionsPvtLtd/audio_waveforms#156]
Sometimes i am stuck at "PlayerState.paused" when the audio has finished playing i start the audio with "   audioplayer.startPlayer(finishMode: FinishMode.pause);" 
If i want to "preparePlayer" a new Audiofile the async method takes unlimited time and never finishes. 

Is there a way to "reset" the audioplayer when i am stuck ? 
I noticed the same behaviour after i called the stopPlayer method, or when i tried changeing audio files while the player was playing
I wasn't able to "reset" the player.

**Comment by ujas-m-simformsolutions** [comment]
Hello @HenrikH96, I quickly made this function and added at the end of the initState of the waveBubble from the example app to reproduce the issue,
```
File? file2;
...

Future<void> changeAudioFile()async{
    await Future.delayed(const Duration(seconds: 5));

    file2 = File('${widget.appDirectory.path}/audio${widget.index! + 1}.mp3');
    await file2?.writeAsBytes(
        (await rootBundle.load('assets/audios/audio${widget.index! + 1}.mp3'))
            .buffer
            .asUint8List());
   await  controller.preparePlayer(
      path: file2!.path,
      shouldExtractWaveform:  true,
    );
    await controller.startPlayer(finishMode: FinishMode.stop);
  }
```
This function will change audio file after 5 seconds while playing the first audio file. I tried this on an iphone 14 pro simulator and I wasn't able to reproduce this with either FinishMode being stop or pause. So please provide minimal reproducible code so that we can debug this.

**Comment by HenrikH96** [comment]
@ujas-m-simformsolutions First of all thank you for your fast response. 
I wasn't able to set up a simple crash yet.  I will try to set it up for the other cases i noticed earlier.

For now i can send u my logs. 
My audiofiles are encrypted and uploaded to a backend and needs to be decrypted first .When new Audio gets uploaded i try to reprepare the Player with following code (the same code works if it is run for the first time):
`  await audioContent
          .decryptAudio(audioContent.audioLink!)
          .then((value) async {
        print(audioplayer.playerState);
        print("finished Decrypting");
        print("set up decrypted audio from path ${audioContent.decryptedAudio!.path}");
        await audioplayer.preparePlayer(
            path: audioContent.decryptedAudio!.path,
            shouldExtractWaveform: false);
        print("audio should be set up");
      });`
      
    But the code never reaches the last print.

I/flutter ( 2917): finished Decrypting
I/flutter ( 2917): set up decrypted audio from path /data/user/0/com.jourries.client/cache/PTT-20181230-WA0008audio.opus
I/ExoPlayerImpl( 2917): Init 8240ad4 [ExoPlayerLib/2.17.1] [panther, Pixel 7, Google, 33]
I/DMCodecAdapterFactory( 2917): Creating an asynchronous MediaCodec adapter for track type audio
D/CCodec  ( 2917): allocate(c2.android.opus.decoder)
I/CCodec  ( 2917): setting up 'default' as default (vendor) store
I/CCodec  ( 2917): Created component [c2.android.opus.decoder]
D/CCodecConfig( 2917): read media type: audio/opus
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 2917): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 2917): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 2917): c2 config diff is Dict {
D/CCodecConfig( 2917):   c2::u32 coded.bitrate.value = 6000
D/CCodecConfig( 2917):   c2::u32 input.buffers.max-size.value = 5760
D/CCodecConfig( 2917):   c2::u32 input.delay.value = 0
D/CCodecConfig( 2917):   string input.media-type.value = "audio/opus"
D/CCodecConfig( 2917):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 2917):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 2917):   c2::u32 raw.sample-rate.value = 48000
D/CCodecConfig( 2917): }
I/MediaCodec( 2917): MediaCodec will operate in async mode
D/CCodec  ( 2917): [c2.android.opus.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 2917): no c2 equivalents for csd-1
D/CCodecConfig( 2917): no c2 equivalents for csd-2
D/CCodecConfig( 2917): no c2 equivalents for flags
W/Codec2Client( 2917): query -- param skipped: index = 1107298332.
D/CCodec  ( 2917): encoding statistics level = 0
D/CCodec  ( 2917): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 2917):   int32_t bitrate = 6000
D/CCodec  ( 2917):   int32_t channel-count = 1
D/CCodec  ( 2917):   int32_t max-input-size = 5760
D/CCodec  ( 2917):   string mime = "audio/opus"
D/CCodec  ( 2917):   int32_t sample-rate = 48000
D/CCodec  ( 2917): }
D/CCodec  ( 2917): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 2917):   int32_t channel-count = 1
D/CCodec  ( 2917):   string mime = "audio/raw"
D/CCodec  ( 2917):   int32_t sample-rate = 48000
D/CCodec  ( 2917):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 2917): }
I/CCodecConfig( 2917): query failed after returning 7 values (BAD_INDEX)
D/MediaCodec( 2917): keep callback message for reclaim
W/Codec2Client( 2917): query -- param skipped: index = 1342179345.
W/Codec2Client( 2917): query -- param skipped: index = 2415921170.
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544c4a08 : 0(0 size) total buffers - 0(0 size) used buffers - 212/217 (recycle/alloc) - 6/432 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544e5008 : 2(11520 size) total buffers - 2(11520 size) used buffers - 1955/1960 (recycle/alloc) - 5/3912 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5447ff98 : 3(17280 size) total buffers - 3(17280 size) used buffers - 2853/2866 (recycle/alloc) - 13/5722 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544479b8 : 3(17280 size) total buffers - 3(17280 size) used buffers - 737/742 (recycle/alloc) - 5/1474 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54478bf8 : 3(17280 size) total buffers - 3(17280 size) used buffers - 737/742 (recycle/alloc) - 5/1474 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544f57a8 : 2(11520 size) total buffers - 2(11520 size) used buffers - 523/528 (recycle/alloc) - 5/1048 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544d0308 : 0(0 size) total buffers - 0(0 size) used buffers - 550/561 (recycle/alloc) - 22/1110 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5449a478 : 2(11520 size) total buffers - 2(11520 size) used buffers - 695/700 (recycle/alloc) - 5/1392 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54482b88 : 0(0 size) total buffers - 0(0 size) used buffers - 26/31 (recycle/alloc) - 9/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544e4228 : 0(0 size) total buffers - 0(0 size) used buffers - 782/793 (recycle/alloc) - 13/1574 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544a51e8 : 3(17280 size) total buffers - 3(17280 size) used buffers - 1907/1912 (recycle/alloc) - 5/3814 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544cab28 : 1(8192 size) total buffers - 1(8192 size) used buffers - 67/72 (recycle/alloc) - 5/70 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54510818 : 0(0 size) total buffers - 0(0 size) used buffers - 25/31 (recycle/alloc) - 12/31 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54534ed8 : 0(0 size) total buffers - 0(0 size) used buffers - 26/31 (recycle/alloc) - 9/31 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5447dce8 : 0(0 size) total buffers - 0(0 size) used buffers - 166/171 (recycle/alloc) - 16/167 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5452a3b8 : 2(16384 size) total buffers - 2(16384 size) used buffers - 154/159 (recycle/alloc) - 5/156 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54569ae8 : 0(0 size) total buffers - 0(0 size) used buffers - 183/188 (recycle/alloc) - 15/185 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54498d58 : 1(5760 size) total buffers - 1(5760 size) used buffers - 287/292 (recycle/alloc) - 5/578 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54515da8 : 0(0 size) total buffers - 0(0 size) used buffers - 72/77 (recycle/alloc) - 8/152 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5452fb98 : 0(0 size) total buffers - 0(0 size) used buffers - 25/31 (recycle/alloc) - 15/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54562be8 : 0(0 size) total buffers - 0(0 size) used buffers - 26/31 (recycle/alloc) - 9/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544a7b88 : 0(0 size) total buffers - 0(0 size) used buffers - 25/31 (recycle/alloc) - 16/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c5454c0d8 : 0(0 size) total buffers - 0(0 size) used buffers - 26/31 (recycle/alloc) - 10/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54485088 : 0(0 size) total buffers - 0(0 size) used buffers - 25/31 (recycle/alloc) - 15/60 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c545078b8 : 0(0 size) total buffers - 0(0 size) used buffers - 320/326 (recycle/alloc) - 20/640 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c544c6128 : 0(0 size) total buffers - 0(0 size) used buffers - 75/80 (recycle/alloc) - 5/158 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54448798 : 3(17280 size) total buffers - 3(17280 size) used buffers - 1907/1912 (recycle/alloc) - 5/3814 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c54569d38 : 0(0 size) total buffers - 0(0 size) used buffers - 26/31 (recycle/alloc) - 10/60 (fetch/transfer)
D/CCodecBufferChannel( 2917): [c2.android.opus.decoder#636] Created input block pool with allocatorID 16 => poolID 67 - OK (0)
D/BufferPoolAccessor2.0( 2917): bufferpool2 0xb400007c545683c8 : 0(0 size) total buffers - 0(0 size) used buffers - 8/13 (recycle/alloc) - 3/6 (fetch/transfer)
D/BufferPoolAccessor2.0( 2917): Destruction - bufferpool2 0xb400007c545683c8 cached: 0/0M, 0/0% in use; allocs: 13, 62% recycled; transfers: 6, 50% unfetched
I/CCodecBufferChannel( 2917): [c2.android.opus.decoder#636] Created output block pool with allocatorID 16 => poolID 685 - OK
D/CCodecBufferChannel( 2917): [c2.android.opus.decoder#636] Configured output block pool ids 685 => OK
D/BufferPoolAccessor2.0( 2917): evictor expired: 1, evicted: 0

**Comment by HenrikH96** [comment]
I don't know what was going on but it seems to work now. 
i just "force" stopp the player when the audiofile should change.
