### ISSUE TITLE
Is there any way to get recorded duration?

### ISSUE THREAD

**Issue by lokishengoku** [SimformSolutionsPvtLtd/audio_waveforms#157]
Great package! I need something like this for our app. Is there any way that I can get the `recorded duration` while recording? Thanks.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/53529954/217223748-a7a4f71f-bf1b-46e3-84bf-898247710154.png">

**Comment by ujas-m-simformsolutions** [comment]
Right now, there aren't any apis to get recorded duration but this is a great suggestion will be adding this to the package.

**Comment by HoangHieuHBR** [comment]
I read in description of onRecordingEnded method. The duration just show when audio recorder has been stopped so how to display the duration while recording. Can you give me an example for that.
