### ISSUE TITLE
How can I ask permission before use audio_waveforms page

### ISSUE THREAD

**Issue by alphatero** [SimformSolutionsPvtLtd/audio_waveforms#160]
**Is your feature request related to a problem? Please describe.**
How can I ask permission before in audio_waveforms page in IOS ?
Because when user first time recorded, will ask permission but audio_waveforms didn't view.

**Comment by ujas-m-simformsolutions** [comment]
Hey @alphatero, you can use `checkPermission` function available in the `RecorderController()`. 

You can initialize the instance of RecorderController before the view comes and use the function and then use same instance  in your view with some state management.

**Comment by alphatero** [comment]
Hi @ujas-m-simformsolutions  , thank you for your reply. It's work for me. Just a suggestion, maybe can put methods in usage document.

This plugin really usfeul! Thank you!
