### ISSUE TITLE
permission in ios

### ISSUE THREAD

**Issue by RamiHI** [SimformSolutionsPvtLtd/audio_waveforms#164]
**Describe the bug**
When the user rejects the permission in ios and re-presses the audio recording, the permission dialog does not appear again

**To Reproduce**
1. Click not allow in dialog
2. re press recoed audio

**Expected behavior**
Reappear the dialog

**Smartphone (please complete the following information):**
- Device: [iPhone12]
- OS: [iOS14.2]
- Version [15.6.1]

**Comment by ujas-m-simformsolutions** [comment]
Hey @RamiHI, when user rejects the permission directly then you can not show permission dialog again. You have to guide them to open settings and enable permission from there or use other package to open your app's permission page in the settings.

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue for now, feel free to reopen or create a new issue.
