### ISSUE TITLE
doesn't start player after stopped !!

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [SimformSolutionsPvtLtd/audio_waveforms#168]
I use `ctrl.startPlayer(finishMode: FinishMode.stop);` to play the audio,
then I use 
```
voicePlayers[voiceFilePath]!.onCompletion.listen((event) async{
  voicePlayers[voiceFilePath]!.startPlayer();
});
```
to restart but it doesn't play
I'm using `audio_waveforms: ^1.0.1`

**Comment by MohammedSalehelShazly** [comment]
I tried to upgrade to `^1.0.2` but the issue still does.

**Comment by ujas-m-simformsolutions** [comment]
@MohammedSalehelShazly When you use `startPlayer(finishMode: FinishMode.stop)` to play audio, it will dispose player when audio is finished playing. So you have to use `preparePlayer` again to use player again

But If want to loop the player just use this `startPlayer(finishMode: FinishMode.loop)`. And if you just want it be paused then use `startPlayer(finishMode: FinishMode.pause)`, it will pause the audio when finished playing.

**Comment by ujas-m-simformsolutions** [comment]
I'm going to close this issue for now. If you are still facing the issue, feel free to reopen the issue.

**Comment by NiklasFoP** [comment]
Thank you so much!! I can confirm that it's working properly now!! <3
