### ISSUE TITLE
Once you have called dispose() on a PlayerController, it can no longer be used.

### ISSUE THREAD

**Issue by Nico3652** [SimformSolutionsPvtLtd/audio_waveforms#171]
Inside my chat app when the user is scrolling very fast through its chat history, my audio widgets are initialized & disposed almost at the same time because of scrolling speed and I get this error :

```
flutter: A PlayerController was used after being disposed.
Once you have called dispose() on a PlayerController, it can no longer be used.
flutter: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:157:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:164:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:360:27)
#3      PlayerController.preparePlayer.<anonymous closure> (package:audio_waveforms/src/controllers/player_controller.dart:123:11)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

Inside the ```initState()``` I'm just calling ```prepaprePlayer()```
And then inside the ```dispose()``` I'm calling ```controller.dispose()``` : 

So because of the ```notify``` here :  

```
Future<void> preparePlayer({
    required String path,
    double? volume,
    bool shouldExtractWaveform = true,
    int noOfSamples = 100,
  }) async {
    path = Uri.parse(path).path;
    final isPrepared = await AudioWaveformsInterface.instance
        .preparePlayer(path, playerKey, volume);
    if (isPrepared) {
      _maxDuration = await getDuration();
      _setPlayerState(PlayerState.initialized);
    }

    if (shouldExtractWaveform) {
      extractWaveformData(
        path: path,
        noOfSamples: noOfSamples,
      ).then(
        (value) {
          waveformData
            ..clear()
            ..addAll(value);
          notifyListeners();
        },
      );
    }
    notifyListeners();
  }
```
I'm getting the error because the dispose is called faster than the notify.

--------------------------------------------------------------------------------------------

Inside my own notifiers, I'm applying this logic to handle this case : 

```
class Model extends ChangeNotifier {
.........

bool _disposed = false;

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  @override
  void notifyListeners() {
    if (!_disposed) {
      super.notifyListeners();
    }
  }
}
```

Is it possible for you to add this in order to avoid notifying when the controller is disposed ? Or what workaround could you suggest ?

**Comment by ujas-m-simformsolutions** [comment]
I totally agree with you, we should only notify when controller isn't disposed.

**Comment by Tom3652** [comment]
hello @ujas-m-simformsolutions thanks for merging this, however i am still seeing this error using `1.0.3` is it normal ?

**Comment by Ujas-Majithiya** [comment]
@Tom3652 Actually it is merged but haven't been released to pub.dev. It will be available in 1.0.4. There is some testing required in other feature that's why it hasn't been released yet.

**Comment by Tom3652** [comment]
Oh alright thanks, i didn't see it in the changelog so i was not sure if it was merged or not, thanks for confirmation !

**Comment by Tom3652** [comment]
@ujas-m-simformsolutions thanks for your work really appreciated
