### ISSUE TITLE
Generate waveform from an URL? 

### ISSUE THREAD

**Issue by ikramhasan** [SimformSolutionsPvtLtd/audio_waveforms#20]
Great package! I needed something just like this for our app. The documentation shows how to generate a waveform by recording audio. But is there a way to generate waveforms from an URL or local audio file? Thanks.

**Comment by ujas-m-simformsolutions** [comment]
Hello @ikramhasan, Thank you for first issue. Unfortunately, you can't generate waveforms from url or local audio files. But we are currently working on that feature. I will update here whenever it get's released.

**Comment by ujas-m-simformsolutions** [comment]
@ikramhasan and everybody waiting for this, we have released `audio_waveforms: ^0.1.1` with this feature. Check it out [here](https://pub.dev/packages/audio_waveforms)
