### ISSUE TITLE
enable seek gesture in paused mode

### ISSUE THREAD

**Issue by woolfman007** [SimformSolutionsPvtLtd/audio_waveforms#200]
First of all, this is a fantastic package, excellent work! I'd suggest to enable seek gestures also when playback is paused. I changed that locally and it seems to work well:

in `PlayerController.seekTo()` I use 

```
if (_playerState == PlayerState.playing || _playerState == PlayerState.paused)
```

instead of 

```
if (_playerState == PlayerState.playing)
```

Also, seekTo() most of the time does not refresh the displayed waveform in that case. I can seekTo(0) and the next call to startPlayer() will correctly start from the beginning; however, the waveform position is not updated.

**Comment by p4-k4** [comment]
I can't get `seekTo(0)` to reset the waveform seek position at all actually.

**Comment by p4-k4** [comment]
@woolfman007 I've added the ability to specify whether or not the waveform resets its playhead position on my fork. See here:

https://github.com/SimformSolutionsPvtLtd/audio_waveforms/commit/8a46a4a984762960ef4ba9c1941ceadabab67466

I just have no idea how to use git to put in a PR lol

**Comment by DevTello** [comment]
Would be nice to have this feature. @ujas-m-simformsolutions, do you plan to update the package anytime soon?

**Comment by himanshuGandhiSimform** [comment]
Yes @DevTello, we are working on this and try to given update ASAP

**Comment by Ruben-HSE** [comment]
When is this fix expected to be released? Do you have any updates?

Thanks in advance for your help!

**Comment by rubenRoehner** [comment]
When is this fix expected to be released? Do you have any updates for us?

Thank you in advance for your help!

**Comment by Ujas-Majithiya** [comment]
> When is this fix expected to be released? Do you have any updates for us?
> 
> 
> 
> Thank you in advance for your help!

We currently have one PR for this #272. But our next release will have some breaking changes so it might take some time to release a new version.
