### ISSUE TITLE
audio record on IOS don't work. error : CreateDataFile failed

### ISSUE THREAD

**Issue by mathieusoufflard** [SimformSolutionsPvtLtd/audio_waveforms#209]
**Describe the bug**
Ass the issue #106 ios microphone is not working and not display Waveforms.
I don't have orange point on top the microphone is not opened
I check the permission
I change the sampleRate and bitRate
I also try to change the iosEncoder
nothing change it's still don't work
work on Android

**To Reproduce**

```
late final RecorderController _waveController;
  List<File> _audioFile = [];
  bool _isRecorderReady = false;
  bool _recording = false;
```

```
@override
  void initState(){
    super.initState();
    _waveController = RecorderController();
    _waveController.sampleRate = 44100;
    _waveController.bitRate = 48000;
    _waveController.iosEncoder = IosEncoder.kAudioFormatMPEG4AAC;         // Changing ios encoder
    _isRecorderReady = true;
  }
```

```
_audioWave() =>Align(
    alignment: Alignment.centerRight,
    child: AudioWaveforms(
      waveStyle: const WaveStyle(
        durationLinesColor: Colors.white,
        waveColor: Colors.black,
        showDurationLabel: true,
        spacing: 12,
        extendWaveform: true,
        showMiddleLine: false,
      ),
      size: Size(MediaQuery.of(context).size.width, 100),
      recorderController: _waveController,
    ),
  );
  ```
```
Future _record() async {
    if(!_isRecorderReady) return;
    await _waveController.record();
    setState(() {
      _recording = !_recording;
    });
  }
```

  ```
Future _stop() async {
    if(!_isRecorderReady) return;
    final path = await _waveController.stop();
    setState(() {
      _recording = !_recording;
    });
    _audioFile.add(File(path!));
  }
  ```

**Smartphone (please complete the following information):**
- Device: iphone 12
- OS: [14.6]
- Podfile: platform :ios, '11.0'
- Flutter version : Flutter 3.9.0-22.0.pre.28
- Dart version :  3.0.0 (build 3.0.0-408.0.dev)

**Comment by Ujas-Majithiya** [comment]
The default encoder is kAudioFormatMPEG4AAC for ios. Also if we don't provide bitRate to ios recorder it works fine.

**Comment by Ujas-Majithiya** [comment]
If you want to have bitRate, you can test different encoders and sample rate. If you think there are any options which are missing please do report.

**Comment by mathieusoufflard** [comment]
still does't work even if I don't change the encoder to keep the default one. same if I don't specify the bitRate.
Anyone have succeed to run in on IOS ?
