### ISSUE TITLE
Waveform timer listener.?

### ISSUE THREAD

**Issue by amsyary** [SimformSolutionsPvtLtd/audio_waveforms#21]
very good package, the waveform audio package in flutter is mostly outdated, I understand this package is still new but one feature that is quite cool I think is the timer listener when the waveform is scrolled we can get the time position of the audio, and we can play the audio right at the scroll position

**Comment by ujas-m-simformsolutions** [comment]
@amsyary  If I understand you correctly, you want an audio player with waveform in which you can tap on any wave position and play audio from there?

**Comment by amsyary** [comment]
Yes, that's right, it will be very useful when we finish recording our voice, scroll through the waveform, and play the audio right on the red line, I can use the audio player library, but I'm still confused about integrating it with this waveform library, this library has a lot of potential to be popular

**Comment by ujas-m-simformsolutions** [comment]
Hey @amsyary, we have released `audio_waveforms: ^0.1.1`. Which has this feature you can check out [here](https://pub.dev/packages/audio_waveforms)
