### ISSUE TITLE
does it support to play audio from url ?

### ISSUE THREAD

**Issue by bermohmtnm** [SimformSolutionsPvtLtd/audio_waveforms#210]
does it support to play audio from url ?

**Comment by FaureAlexis** [comment]
Currently no, you must provide your own implementation : 
```dart
Future<String> downloadAudioFromUrl(String url) async {
  final dir = await getApplicationDocumentsDirectory();
  final path = dir.path;
  final file = File('$path/file.wav');
  final response = await http.get(Uri.parse(url));
  await file.writeAsBytes(response.bodyBytes);
  return file.path;
}
```

**Comment by toufiksalhi** [comment]
same issue

**Comment by toufiksalhi** [comment]
> Currently no, you must provide your own implementation :
> 
> ```dart
> Future<String> downloadAudioFromUrl(String url) async {
>   final dir = await getApplicationDocumentsDirectory();
>   final path = dir.path;
>   final file = File('$path/file.wav');
>   final response = await http.get(Uri.parse(url));
>   await file.writeAsBytes(response.bodyBytes);
>   return file.path;
> }
> ```


this is not good for user experience each time he wanna hear the audio he will found a file of it in his phone ! 
فا

**Comment by campfire5** [comment]
This feature is very urgent.

**Comment by campfire5** [comment]
May we can just have the ability to play it from url, and never mind the wave data, I mean we can still pass the wave data manually.

**Comment by benedictleekw** [comment]
Please prioritize on this feature if possible. Being able to play audio without downloading the audio file would be a huge plus

**Comment by ujas-m-simformsolutions** [comment]
Duplicate of #54
