### ISSUE TITLE
Audio out of sync with waveform in some files during playback

### ISSUE THREAD

**Issue by javad-kh** [SimformSolutionsPvtLtd/audio_waveforms#212]
I have noticed that in some files, the audio is out of sync with the waveform during playback. Specifically, the audio seems to be lagging behind the waveform, creating a noticeable delay in the sound.

I have tested this issue on multiple files and have confirmed that the problem persists. It would be greatly appreciated if the package could be updated to ensure that the audio is in sync with the waveform during playback.

**Comment by himanshuGandhiSimform** [comment]
Hello @javad-kh, if possible can you please share the audio file?

**Comment by javad-kh** [comment]
hello @himanshuGandhiSimform. 
The sound I used to record had this problem during playback, I think I used another package to record the sound

**Comment by jay-simformsolutions** [comment]
Hello, @javad-kh. If you want a smoother experience, please try updateFrequency parameter to high. Because the default value is low for this reason might be you faced this issue.
