### ISSUE TITLE
How to get the dragged position when I grag&move the waveform in AudioFileWaveforms?

### ISSUE THREAD

**Issue by wann2** [SimformSolutionsPvtLtd/audio_waveforms#213]
How to get the dragged position when I drag&move the waveform in AudioFileWaveforms?
I'd like to get the dragged&moved position from AudioFileWaveforms.

**Comment by himanshuGandhiSimform** [comment]
Hello @wann2, Can you please provide more information such as which position you want?

**Comment by manoj-simform** [comment]
Closing this issue as it's fixed in this issue #384.
