### ISSUE TITLE
No support for headphone mic

### ISSUE THREAD

**Issue by soumyajitReev** [SimformSolutionsPvtLtd/audio_waveforms#222]
I can't access the headphone mic while recording with recordcontroller, it only recording with device's default mic even after headphone is connected. please solve the issue ASAP.

**Comment by ujas-m-simformsolutions** [comment]
I tested on IOS and android, it works for IOS but it doesn't on android.

**Comment by himanshuGandhiSimform** [comment]
Hello @soumyajitReev if possible can you please share your device info?

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue since no further information was shared.
