### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method preparePlayer on channel simform_audio_waveforms_plugin/methods))

### ISSUE THREAD

**Issue by mohdnasirbaloch** [SimformSolutionsPvtLtd/audio_waveforms#223]
**Describe the bug**
I am trying to use you package to play audio with generated waves but i am facing exception which states that,
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method preparePlayer on channel simform_audio_waveforms_plugin/methods))

even though i  am using latest version of your package and also imported the file etc everything. 
![image](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/134352837/2f9d4db6-15bf-4052-bbcc-3d4262f12779)

here is my complete code 
import 'package:flutter/material.dart';
import 'package:audio_waveforms/audio_waveforms.dart';

void main() {
  runApp(MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late PlayerController controller;
  List<String> songs = [
    'asset/audio/song.mp3',
  ];

  @override
  void initState() {
    super.initState();
    controller = PlayerController();
    prepareSongs();
  }

  void prepareSongs() async {
    for (var song in songs) {
      await controller.preparePlayer(
        path: song,
        shouldExtractWaveform: true,
        noOfSamples: 100,
        volume: 1.0,
      );
    }
    setState(() {}); // Trigger widget rebuild after preparing songs
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Waveform Player'),
      ),
      body: ListView.builder(
        itemCount: songs.length,
        itemBuilder: (context, index) {
          final song = songs[index];
          return ListTile(
            title: Text(song),
            leading: Container(
              width: 100,
              height: 50,
              child: FutureBuilder<List<double>>(
                future: getWaveformData(song),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return CircularProgressIndicator();
                  } else if (snapshot.hasError) {
                    return Text('Error: ${snapshot.error}');
                  } else if (snapshot.hasData) {
                    final waveformData = snapshot.data!;
                    return WaveformPainter(
                      waveformData: waveformData,
                      width: 100,
                      height: 50,
                    );
                  } else {
                    return const Text('No waveform data');
                  }
                },
              ),
            ),
          );
        },
      ),
    );
  }

  Future<List<double>> getWaveformData(String song) async {
    return await controller.extractWaveformData(
      path: song,
      noOfSamples: 100,
    );
  }
}

class WaveformPainter extends StatelessWidget {
  final List<double> waveformData;
  final double width;
  final double height;

  const WaveformPainter({
    required this.waveformData,
    required this.width,
    required this.height,
  });

  @override
  Widget build(BuildContext context) {
    return CustomPaint(
      painter: _WaveformPainter(waveformData: waveformData),
      size: Size(width, height),
    );
  }
}

class _WaveformPainter extends CustomPainter {
  final List<double> waveformData;

  _WaveformPainter({required this.waveformData});

  @override
  void paint(Canvas canvas, Size size) {
    // Waveform painting logic here
    // Use the waveformData to draw the waveform on the canvas
  }

  @override
  bool shouldRepaint(_WaveformPainter oldDelegate) {
    return waveformData != oldDelegate.waveformData;
  }
}

**Comment by guitoof** [comment]
Hi @mohdnasirbaloch  are on which platform are you trying to run the app? mobile only or web /desktop too?
This package has only support for iOS/Android so the platform channel methods won't exists for web/macos/linux/windows
I don't know if there is any plan to support them yet

**Comment by mohdnasirbaloch** [comment]
Actually I was trying on desktop, then I get to know it will work only on
Android and iOS

**Comment by mohdnasirbaloch** [comment]
Another issue is that it is not picking mp3 files directly, I have to first
decode them then it works

**Comment by Ujas-Majithiya** [comment]
@mohdnasirbaloch If they are in your assets folder then yes right now you have to load them by your self
