### ISSUE TITLE
Add setReleaseMode

### ISSUE THREAD

**Issue by moshOntong-IT** [SimformSolutionsPvtLtd/audio_waveforms#228]
**Is your feature request related to a problem? Please describe.**
We should add a method for finishMode something like in audio player has asetReleaseMode

**Describe the solution you'd like**
We should option that the user will have choices to choose if it enable the loop mode or not

**Comment by Ujas-Majithiya** [comment]
So your proposal is to add a method to set release mode instead of setting it from `startPlayer` right?

**Comment by moshOntong-IT** [comment]
yup that is right we should remove the finishMode parameter in startPlayer, it is prefer to create a setReleaseMode
