### ISSUE TITLE
Stop player should not be freed the resources

### ISSUE THREAD

**Issue by moshOntong-IT** [SimformSolutionsPvtLtd/audio_waveforms#230]
**Is your feature request related to a problem? Please describe.**
As the documentation said, when triggering the stopPlayer it will freed the resources. I think this is not a good idea,  we already have dispose method, programmer always depend on this method to freed all the resources. Stop player should only stop only the audio and back to the start 0 duration. it means stop something like resetting the duration

**Comment by RockStone** [comment]
Same issue here. It seems the message cannot be replayed once it's stopped, unless it's paused instead. @ Ujas-Majithiya
