### ISSUE TITLE
Re-Rendering continues when music stops

### ISSUE THREAD

**Issue by ty1135** [SimformSolutionsPvtLtd/audio_waveforms#231]
1.Re-Rendering continues when music stops

I've read all source code and the problem is:
length in _drawWave will grow as loop continues. 

Reproduce: set samples  = 10000 or even large

2. another bug is that : 10000*double = 0.0763 MB, but somehow memory leaks

**Comment by ty1135** [comment]
Adding this line "Iterable<double> factoredValue = value.map((v) => v * 0).toList();" into the following makes no difference

if (shouldExtractWaveform) {
      extractWaveformData(
        path: path,
        noOfSamples: noOfSamples,
      ).then(
        (value) {
          Iterable<double> factoredValue = value.map((v) => v * 0).toList();
          waveformData
            ..clear()
            ..addAll(factoredValue);
          notifyListeners();
        },
      );

**Comment by ujas-m-simformsolutions** [comment]
Can you please elaborate more on what is the issue?

**Comment by jay-simformsolutions** [comment]
Due to no response, we are closing for now. Feel free to re-open this issue.
