### ISSUE TITLE
not recording internal sound in real device like youtube,sportify

### ISSUE THREAD

**Issue by prashanttechnoyuga** [SimformSolutionsPvtLtd/audio_waveforms#233]
I want to record  internal sound of mobile device like youtube, sportify.

its recording in simulator. but not in real device. 

video link :- https://drive.google.com/file/d/1jCgBOzzajvqdfaJD93Bw6FmsKRqZvUMh/view?usp=sharing

**Comment by jay-simformsolutions** [comment]
Hi @prashanttechnoyuga, can you please provide the valid and working video link so we can check and resolve your query?
