### ISSUE TITLE
Because you have deprecated 'normalisationFactor'.

### ISSUE THREAD

**Issue by csacchetti** [SimformSolutionsPvtLtd/audio_waveforms#235]
Because you have deprecated 'normalisationFactor'. It is one more element to optimise the recording wave together with 'scaleFactor'. Playing on both gives more precise results.
Thanks

**Comment by ujas-m-simformsolutions** [comment]
Instead of playing with normalisationFactor & scaleFactor, I think we should find a permanent solution to normalise the amplitude. Like, which is being used in native packages. I'm going to close this issue. We are open to contribution, if you find a better solution the than current one.
