### ISSUE TITLE
getting `Failed to transform exoplayer-hls-2.17.1.aar` error after install audio_waveforms package

### ISSUE THREAD

**Issue by Miladn96** [SimformSolutionsPvtLtd/audio_waveforms#239]
I add audio_waveforms package on my flutter app but I can't build or run the project. it shows me blow error.

My System Info: Linux Ubuntu: 22.04.3 flutter: 3.10.6 Dart: 3.0.6

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audio_waveforms_fix:generateDebugRFile'.
> Could not resolve all files for configuration ':audio_waveforms_fix:debugCompileClasspath'.
   > Failed to transform exoplayer-hls-2.17.1.aar (com.google.android.exoplayer:exoplayer-hls:2.17.1) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find exoplayer-hls-2.17.1.aar (com.google.android.exoplayer:exoplayer-hls:2.17.1).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-hls/2.17.1/exoplayer-hls-2.17.1.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1`

![image](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/81409485/52987d69-5d57-4442-8a96-5d1930d10aa5)

I try several solution but it doesn't work. and also I asked chat GPT and bard but thay couldn't help me. if anyone face with this issue before please help me.

**Comment by Miladn96** [comment]
I finally find a solution. so If you need to use the audio_waveforms flutter package just install ffmpeg application on your linux.

How install ffmpeg?

1- sudo apt-get install software-properties-common

2- sudo add-apt-repository ppa:mc3man/trusty-media

3- sudo apt-get update

4- sudo apt-get dist-upgrade

5- sudo apt-get install ffmpeg

bingoo now I can use audio_waveforms package in my project.

[How to Install FFmpeg on Linux](https://www.hostinger.com/tutorials/how-to-install-ffmpeg#Installing_FFmpeg_on_Ubuntu)

**Comment by ujas-m-simformsolutions** [comment]
@Miladn96 We have merged a PR which fixes gradle issues and we will release it soon. Thanks for your patience.

**Comment by Miladn96** [comment]
> @Miladn96 We have merged a PR which fixes gradle issues and we will release it soon. Thanks for your patience.
@ujas-m-simformsolutions Thanks

**Comment by ujas-m-simformsolutions** [comment]
@Miladn96 Can you please confirm latest release fixed your issue?
