### ISSUE TITLE
Trying to change from AndroidOutputFormat.mpeg4 to AndroidOutputFormat.aac which the plugin doesn't do.

### ISSUE THREAD

**Issue by paramkansagra** [SimformSolutionsPvtLtd/audio_waveforms#244]
**Describe the bug**
When we want to change the type of output in android i.e. from m4a to aac. The library doesnt do the same.

Code:-

recorderController = RecorderController() // init the recorder
      ..androidEncoder = AndroidEncoder
          .aac // the encoder we should be using for android for performance and support
      ..androidOutputFormat =
          AndroidOutputFormat.mpeg4 // the output format for android support
      ..iosEncoder = IosEncoder
          .kAudioFormatMPEG4AAC // ios encoder which basically has both the output format and encoder in onc
      ..sampleRate = 44100 // best sample rate for voice
      ..updateFrequency = const Duration(
          milliseconds: 180); // aprox 3fps for recording waveform

Tryng to change from AndroidOutputFormat.mpeg4 to AndroidOutputFormat.aac which the plugin doesnt do.

**Expected behavior**
The plugin should export in aac format.

**Smartphone (please complete the following information):**
- All Android Phones

**Comment by himanshuGandhiSimform** [comment]
Hello @paramkansagra, you can change the type of output to aac by doing the following steps.

- change the type of output file example `dir1/dir2/file-name.aac`
- select **aac_adts** option for androidOutputFormat

**Comment by himanshuGandhiSimform** [comment]
with the above steps its working well so closing this issue for now.
