### ISSUE TITLE
AudioWaveforms with RecorderController does not show any waves

### ISSUE THREAD

**Issue by vongrad** [SimformSolutionsPvtLtd/audio_waveforms#247]
**Describe the bug**
I cloned audio_waveforms GitHub repo, opened up the example project and ran it on iPhone 14 Pro (iOS 16.4) emulator, however the waves are shown when recording the audio. (I have not modified any of your code)

**To Reproduce**
1. Clone audio_waveforms repo
2. Open up the example project
3. Run it on iOS emulator (16.4)
4. Start recording the sound
5. No visual waves are shown, just dots with [x*t, 0]

**Expected behavior**
The waves should react to recorded audio.

**Smartphone (please complete the following information):**
- Device: iPhone 14 Pro (emulator)
- OS: IOS 16.4

**Comment by hossam-96** [comment]
I have the same issue with my phone
Phone Model: Realme 5 pro
Android Version: 10

It works fine with the rest of emulators and devices ( Android & iOS )

**Comment by Priyanshu85** [comment]
I got the same issue, did you get any solutions?

**Comment by Ujas-Majithiya** [comment]
@vongrad Can please use the new `1.0.5` version and #242 might have had fixed this.

**Comment by jt274** [comment]
I am also experiencing this on a physical device, iOS 17.4.1. Latest version `1.0.5`.

**Comment by Heropowwa** [comment]
I've got the same problem using the new version on android

**Comment by Ujas-Majithiya** [comment]
I tested on an iPhone 14 simulator with IOS 17.2 recording waves are generating just fine for me. Did you get any exceptions or logs while recording? If you can share it then I would help us find the issue.

**Comment by Ujas-Majithiya** [comment]
The bitrate value of 48k falls outside of the supported range of mpeg4 audio format on Android. Can you please try a higher bitrate value?

**Comment by Heropowwa** [comment]
What should I set it to?

**Comment by Heropowwa** [comment]
I tried this:```
 void initialiseController() {
    if (isInitialised) {
    } else {
      recorderController = RecorderController()
        ..androidEncoder = AndroidEncoder.aac
        ..androidOutputFormat = AndroidOutputFormat.mpeg4
        ..iosEncoder = IosEncoder.kAudioFormatMPEG4AAC
        ..sampleRate = 44100
        ..bitRate = 128000;
      isInitialised = true;
    }
  }
```
But it sill doesn't show waves while recording.
![Screenshot_2024-05-07-13-43-41-466_com example chat](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/88487533/93f85aad-3039-4a11-9eaf-b7c1c8dc3719)

**Comment by Heropowwa** [comment]
```
 void initialiseController() {
    if (isInitialised) {
    } else {
      recorderController = RecorderController()
        ..androidEncoder = AndroidEncoder.opus
        ..androidOutputFormat = AndroidOutputFormat.ogg
        ..iosEncoder = IosEncoder.kAudioFormatOpus
        ..sampleRate = 44100;
      isInitialised = true;
    }
  }
```
I've changed to these settings and now it works.

**Comment by himanshuGandhiSimform** [comment]
due to no recent updates we closing this for now.
