### ISSUE TITLE
AudioWaveforms does not remove listeners properly

### ISSUE THREAD

**Issue by jellynoone** [SimformSolutionsPvtLtd/audio_waveforms#249]
**Describe the bug**
The way AudioWaveforms is written it never removes the listener it attaches.
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/ea69c5ec00e5c7a18b8d87d22999ad5c4ddf71ca/lib/src/audio_waveforms.dart#L45-L56

Since the listener is a closure it will not be removed. The listener needs to be a method of the class for the widget to be able to remove it from the list of listeners.

This bug is being hidden away by the `if (mounted)` check before `setState`. However, that is just a workaround to the fact the listener is not being removed.

In addition, while looking at this widget it seems sub-optimally structured, it rebuilds way too much.
The only thing that depends on the values produced by the controller is the painter, and since the controller is a Listenable it can be passed to the `CustomPainter.repaint` property. This would then avoid rebuilding the widget all together and simply have the painter repaint, skipping a whole lot of work in the process.

**Expected behavior**
The AudioWaveforms widget should correctly remove the listeners it attaches.

**Comment by ujas-m-simformsolutions** [comment]
Fixed in latest release.
