### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by alireza-hnzpv** [SimformSolutionsPvtLtd/audio_waveforms#253]
waveformData = await _playerController.extractWaveformData(path: await loadAsset('assets/sound/notification/notification_sound1.mp3'));

E/flutter (21446): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 45)
E/flutter (21446): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
E/flutter (21446): #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
E/flutter (21446): #2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
E/flutter (21446): #3      AssetBundle._utf8decode (package:flutter/src/services/asset_bundle.dart:102:17)
E/flutter (21446): #4      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19:20)
E/flutter (21446): #5      _RemoteRunner._run (dart:isolate:1021:47)
E/flutter (21446): #6      _RemoteRunner._remoteExecute (dart:isolate:1015:12)
E/flutter (21446): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
E/flutter (21446): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (21446): 
D/EGL_emulation(21446): app_time_stats: avg=36.47ms min=9.18ms max=528.05ms count=28

**Comment by himanshuGandhiSimform** [comment]
Hello @alireza-hnzpv, can you please provide loadAsset method source code?

**Comment by himanshuGandhiSimform** [comment]
Closing this issue for now since no more information was provided. Please, feel free to create new one.
