### ISSUE TITLE
I encountered a bug when using the audio_waveforms package version 1.0.4. After my recording is interrupted by another application, I expect to be able to resume recording by clicking the record button again without having to restart the application.

### ISSUE THREAD

**Issue by 2971026328** [SimformSolutionsPvtLtd/audio_waveforms#254]
Describe the bug
I encountered a bug when using the audio_waveforms package version 1.0.4. After my recording is interrupted by another application, I expect to be able to resume recording by clicking the record button again without having to restart the application.

To Reproduce

Open the application '...'
Navigate to the recording feature '...'
Start recording by clicking '...' button.
While recording, have another application interrupt the recording (e.g., receiving a phone call or using another audio app).
Stop the interruption and attempt to resume recording by clicking the record button again.
Observe that it's not possible to resume recording by clicking the button, and the application needs to be restarted.
Smartphone Information:

Device: Xiaomi 12
Operating System: Android 13
Version: audio_waveforms 1.0.4
Additional context
This issue disrupts the user experience and makes the application's audio recording feature less reliable. Resolving this bug will help ensure that recording can be resumed by clicking the record button without the need to restart the application.

**Comment by himanshuGandhiSimform** [comment]
Hello @2971026328, we have methods for pause the recording and you can also resume the recording using record method so based on that you can manage your recording according to your requirement.

**Comment by himanshuGandhiSimform** [comment]
due to no recent updates we closing this for now.
