### ISSUE TITLE
Allow Bluetooth Output Devices

### ISSUE THREAD

**Issue by jbryanh** [SimformSolutionsPvtLtd/audio_waveforms#256]
**Is your feature request related to a problem? Please describe.**
When .record is called, your code overrides any audio session that has been previously configured. 

let options: AVAudioSession.CategoryOptions = [.defaultToSpeaker, .allowBluetooth] seems to override.

**Describe the solution you'd like**
The most popular audio session plugin, [audio_session](https://pub.dev/packages/audio_session) states: 
"Note that iOS (and hence this plugin) provides a single audio session to your app which is shared by all of the different audio plugins you use. If your app uses multiple audio plugins, e.g. any combination of audio recording, text to speech, background audio, audio playing, or speech recognition, then it is possible that those plugins may internally overwrite each other's choice of these global system audio settings, including the ones you set via this plugin. Therefore, it is recommended that you apply your own preferred configuration using audio_session after all other audio plugins have loaded. **You may consider asking the developer of each audio plugin you use to provide an option to not overwrite these global settings and allow them be managed externally.**"

**Comment by appinteractive** [comment]
Any updates on this?

**Comment by juskuc** [comment]
This saved me in debugging a tough issue with call-kit/webrtc/this plugin causing various audio issues. Thanks for letting us know about the override!
