### ISSUE TITLE
Clear waveData

### ISSUE THREAD

**Issue by clemortel** [SimformSolutionsPvtLtd/audio_waveforms#26]
Hey, what a great package, very good job !

I have used to record and after I want to preview it, it works fine but I want to clear the waveData manually and I've seen it's not possible since the method reset is private.

Could you made it public to let us use it ?

Thanks a lot !

**Comment by ujas-m-simformsolutions** [comment]
Hey @clemortel, yes after releasing the first thing I noticed was this so if you check this [PR](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/pull/23), it is resolved there. But that PR had some issue with multiple players so that's why it has not been merged yet.

**Comment by ujas-m-simformsolutions** [comment]
Hey @clemortel we have released `audio_waveforms: ^0.1.1` which fixes this issue you can check out [here](https://pub.dev/packages/audio_waveforms)
