### ISSUE TITLE
How to replay currnet file after finishing ?

### ISSUE THREAD

**Issue by khaledelsherbiny** [SimformSolutionsPvtLtd/audio_waveforms#261]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khaledelsherbiny** [comment]
Can i seek during pause ?

**Comment by DevarshRanpara** [comment]
Hello @khaledelsherbiny 
Can you share us more details about the issue you are facing please?

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue for now. Feel free to create a new one if you have any other issues.
