### ISSUE TITLE
fetch from phone directory and show , also play from that list.

### ISSUE THREAD

**Issue by mrugesha8** [SimformSolutionsPvtLtd/audio_waveforms#263]
i want to record audio and save on phone directory.

also i fetch from there and show in another page and aslo when i click on that list's any file then it's play .
i tried but i didn't able to do that so please give me suggestion.

**Comment by DevarshRanpara** [comment]
Hello @mrugesha8 ,
Can you let us know what is the behaviour of your project when you click on any file? Are you facing any error, application is crashing or any other issues?
If you can share us more details about the system's behaviour and share us some code, it would be really helpful for us.

**Comment by Ujas-Majithiya** [comment]
@mrugesha8 You can refer to [example](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/example/lib/main.dart) app to achieve what you have described.

Closing this issue for now. Feel free to create a new one if you face any other issues.
