### ISSUE TITLE
missing plugin issue

### ISSUE THREAD

**Issue by MoazzamAliSE** [SimformSolutionsPvtLtd/audio_waveforms#273]
MissingPluginException(No implementation found for method checkPermission on channel simform_audio_waveforms_plugin/methods)

I am facing this issue while starting recording.
I tried everything like pod install, pod update etc
also my info.plist is all ok
android side is working perfectly but there is one more things when i come back from screen the audio still running in background.
Although this package is so amazing ..
but how can i fix this issue which is occuring while i start recording
i also have implemented permission handler to get the microphone access . but still missing plugin excetion was there...

void startRecording() async {
 
    try {

      audioPath = await _getPath();

      if (await _audioRecorder.checkPermission()) {

      await _audioRecorder.record(path: audioPath);
      _recordDuration = 0;
      _startTimer();
      _isRecording = true;
      update();
      }
    } catch (e) {
      print("exception in Recording Audio $e");
    }
  }
  
    Future<String> _getPath() async {
    directory = await getApplicationDocumentsDirectory();
    final uniqueId = DateTime.now().millisecondsSinceEpoch;
    return p.join(
      directory.path,
      'audio_$uniqueId.m4a',
    );
  }

**Comment by ujas-m-simformsolutions** [comment]
@MoazzamAliSE If app is already installed in your IOS device, then uninstall it and try to run it again. If it still doesn't work, then try `flutter clean`.

**Comment by MoazzamAliSE** [comment]
Thank you.
