### ISSUE TITLE
`stopAllPlayers()` , `pausePlayer()` and `stopPlayer()` doesn't work on `AppLifeCycleState.detached` in Android Devices.

### ISSUE THREAD

**Issue by nemr0** [SimformSolutionsPvtLtd/audio_waveforms#277]
**Describe the bug**
Running the following methods of PlayerController doesn't work on android device app termination.
- `playerController.stopAllPlayers()`
- `pausePlayer()`
- `stopPlayer()`

**To Reproduce**
- add `WidgetsBindingObserver` to a StatefulWidget
- add the following to the `didChangeAppLifecycleState(AppLifecycleState state)` function:
``` 
 /// On App Termination
      case AppLifecycleState.detached:
        playerController.stopAllPlayers();
```

**Expected behavior**
- Should stop audio.
- what actually happens that audio keeps running in background with no controls nor app  (removing from recent), only happens in android devices.

**Smartphone:**
- Device: `Samsung Galaxy A13`
- OS: Android `13.0`
- Flutter SDK Version: `3.13.9` 
- Package Version: `^1.0.4`

**Comment by nemr0** [comment]
@yohom @tejas-ardeshna @BirjuVachhani @rlee1990 guys could you help please and thank you.

**Comment by Ujas-Majithiya** [comment]
@nemr0 When you are killing the it's not guaranteed that code for detached state. Also, when app goes in the detached state first thing that gets closed is method channel so native calls won't be executed. Before detached state, app goes to inactive state, so what you can do here is call method for stopping player there.

We will see if we can stop player from native when app is killed otherwise will close this as `wontfix`.

**Comment by nemr0** [comment]
> @nemr0 When you are killing the it's not guaranteed that code for detached state. Also, when app goes in the detached state first thing that gets closed is method channel so native calls won't be executed. Before detached state, app goes to inactive state, so what you can do here is call method for stopping player there.
> 
> 
> 
> We will see if we can stop player from native when app is killed otherwise will close this as `wontfix`.

It should stop the sound from the native side this behavior already applies to iOS but in Android it keeps playing without a way to stop, just_audio kills the sound on android app kill i recommend to check it's native code and thank you

**Comment by Ujas-Majithiya** [comment]
@nemr0 Thank you for your recommendation, we will check it as soon as possible.

**Comment by Ujas-Majithiya** [comment]
I checked on a Pixel 6a audio gets stopped after `killing` the app even without stopping the player in the **didChangeAppLifecycleState**. I think this can be a device specific issue. We will have to test it on a samsung device.

**Comment by DhavalRKansara** [comment]
@nemr0  Could you please share the device info in which you are facing this issues so we can try to replicate the the same on our end?

**Comment by MINEGHOST007** [comment]
even i am facing this same issue like i have a player and a recorder it sometimes works sometimes wont please fix ..

**Comment by nemr0** [comment]
> @nemr0  Could you please share the device info in which you are facing this issues so we can try to replicate the the same on our end? 

Sorry for late reply, so it actually happens randomly probs because detached is not always called, but it happens more frequently if you use audio_service package to use native controls.

Thanks for your help.

**Comment by ujas-m-simformsolutions** [comment]
@MINEGHOST007 Are you also using using the audio_service package? Can you please check if solution shared by nemro fixes your issue.

**Comment by ujas-m-simformsolutions** [comment]
Since original issue was not related to the package I'm going to close this issue. If you're facing similar issue with different scenario then please file a new issue.
