### ISSUE TITLE
Using with Twilio

### ISSUE THREAD

**Issue by waiphyo-0gravity** [SimformSolutionsPvtLtd/audio_waveforms#281]
Currently I am trying to use twilio with audio_waveforms but the wave pitches are always 0. 
PS. If i commend the twilio code, waves work properly.
Can you help me with this? I'm also using record audio feature from twilio.

**Comment by ujas-m-simformsolutions** [comment]
@waiphyo-0gravity Can please share error logs if there is any? Also it could be happening that twilio and audio waveforms both are trying to use same microphone. Can please share code also?

**Comment by Ujas-Majithiya** [comment]
Closing this issue since no response was provided.
