### ISSUE TITLE
Audio player playing animation completes before audio is completed playing

### ISSUE THREAD

**Issue by miteshp-26** [SimformSolutionsPvtLtd/audio_waveforms#290]
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/115924457/b060dc2e-798e-48f5-ad39-de6b84d1bb72

Greetings,

I'm using this library per following steps

1) Record audio using AudioWaveforms and RecorderController
2) Upload recorded audio to database
3) Load audio from URL using cache manager
4) Prepare player and set audio in AudioFileWaveforms

Now if I use waveformType: WaveformType.long, it is working fine but when using waveformType: WaveformType.fitWidth in AudioFileWaveforms the above mentioned video issue arises,

Hope to get a quick solution,
Thanks & Regards

**Comment by jt274** [comment]
You need to use `controller.getSamplesForWidth()` according to the docs. You first need to determine the width of the widget containing the waveforms, then get the number of samples required for that width, then pass it to `controller.extractWaveformData()`.

You can also see more info in the migration guide: https://github.com/SimformSolutionsPvtLtd/audio_waveforms/blob/main/migration_guide.md

It would be nice for this process to be easier.

**Comment by miteshp-26** [comment]
Thank you @jt274 
It's working very well now

**Comment by jt274** [comment]
@miteshp-26 You're welcome. You can close this issue if it is resolved.

**Comment by DhavalRKansara** [comment]
Hello @miteshp-26, I am closing this issues as it seems @jt274 help you find the fix for your requirement. Please feel free to open a new issue if you have any doubts.
