### ISSUE TITLE
IOS 15.8.2, dyld[616]: Symbol not found

### ISSUE THREAD

**Issue by liugong86** [SimformSolutionsPvtLtd/audio_waveforms#293]
when use Xcode to debug app  on device iPhone 7 , It is false, and  throw a Error.

dyld[616]: Symbol not found: (_$s10Foundation3URLV19_bridgeToObjectiveCSo5NSURLCyF)
  Referenced from: '/private/var/containers/Bundle/Application/63A08836-6705-4B78-B022-864FB9CA8308/Runner.app/Frameworks/audio_waveforms.framework/audio_waveforms'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Foundation'.

**Smartphone (please complete the following information):**
- Device: iPhone 7
- OS: IOS 15.8.2

Can somebody  help me?

**Comment by Ujas-Majithiya** [comment]
@liugong86 I'm not sure about the issue you are having but having tried the command flutter clean?

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue due to no further response
