### ISSUE TITLE
Player can only play the recorded sound once on Android phone.

### ISSUE THREAD

**Issue by jdevp** [SimformSolutionsPvtLtd/audio_waveforms#295]
**Describe the bug**
I'm trying to record a sound and play it back. It works on the recording part but it only allows me to play the sound once. 

**To Reproduce**
1. Initialize Player Controller: `playerController = PlayerController();`
2. Record sound (successfully)
3. Prepare the player:
 
```
getPlayerReady() async{
    String directory = (await getApplicationDocumentsDirectory()).path;
    String dir="$directory/audio";
    print ("$dir/$uKey.aac");
    await playerController!.preparePlayer(
      path: '$dir/$uKey.aac',
      shouldExtractWaveform: true,
      noOfSamples: 100,
      volume: 1.0,
    );
  }
```

4. Play the recorded sound but it plays only first time.

```
IconButton(
            icon: const Icon(  Icons.play_circle,
              color: Colors.green,
            ),
            onPressed: ()async{
            
              print(playerController!.playerState);
              // the first time, the playerState shows Initialized. At end of play, t shows Stopped
              if(playerController!.playerState.isStopped) {
                 print("try to play it again but failed");
                 await playerController!.seekTo(0);
               
                 await playerController!.startPlayer(finishMode: FinishMode.stop);
                 return;
              }
              playerController!.playerState == PlayerState.playing
                  ? await playerController!.pausePlayer()
                  : await playerController!.startPlayer(finishMode: FinishMode.stop);
            }
        ),
```

**Expected behavior**
It should be played every time.

**Smartphone (please complete the following information):**
- Device: [Moto one 5G]
- OS: [Android ]
- Version [11]

**Screenshots**

**Additional context**

**Comment by baraazain** [comment]
are you solve this problem i face it and i try to back versions but the same issues 
and when i seek on ui  and play the audio play from the first

**Comment by baraazain** [comment]
i face the same probleme 
i used 
await controller.startPlayer(finishMode: FinishMode.pause);
and it work 
if you are stop the player you can't run the player again




class AudioWavesMessage extends StatefulWidget {
  final Message message;

  const AudioWavesMessage({super.key, required this.message});

  @override
  State<AudioWavesMessage> createState() => _AudioWavesMessageState();
}

class _AudioWavesMessageState extends State<AudioWavesMessage> {
  PlayerController controller = PlayerController(); // Initialise
  bool isPlaying = false;

  @override
  initState() {
    initialPlayer();
    super.initState();
  }

  @override
  void dispose() {
    stopPlayer();
    controller.dispose();
    super.dispose();
  }

  initialPlayer() async {
    await controller.preparePlayer(
      path: widget.message.files![0].path,
      shouldExtractWaveform: true,
      noOfSamples: 50,
      volume: 1.0,
    );
    controller.onCompletion.listen((state) {
      setState(() {
        pausePlayer();
      });
    });
  }

  startPlayer() async {
    try {
      await controller.startPlayer(finishMode: FinishMode.pause);
      setState(() {
        isPlaying = true;
      });
    } catch (e) {
      print('Error start player: $e');
    }
  }

  pausePlayer() async {
    try {
      await controller.pausePlayer();
      setState(() {
        isPlaying = false;
      });
    } catch (e) {
      print('Error pausing player: $e');
    }
  }

  stopPlayer() async {
    try {
      await controller.stopPlayer();
      setState(() {
        isPlaying = false;
      });
    } catch (e) {
      print('Error stop player: $e');
    }
  }

  @override
  build(BuildContext context) {
    return SizedBox(
      width: 300,
      child: Row(
        children: [
          InkWell(
              onTap: () {
                isPlaying ? pausePlayer() : startPlayer();
              },
              child: Icon(
                isPlaying ? Icons.pause : Icons.play_arrow,
                color: Colors.white,
              )),
          const SizedBox(
            width: 10,
          ),
          Expanded(
            child: AudioFileWaveforms(
              size: Size(MediaQuery.of(context).size.width, 40.0),
              playerController: controller,
              enableSeekGesture: isPlaying ? true : false,
              waveformType: WaveformType.fitWidth,
              waveformData: const [],
              playerWaveStyle: const PlayerWaveStyle(
                  fixedWaveColor: Colors.white,
                  liveWaveColor: DesignColors.green,
                  spacing: 6,
                  seekLineColor: Colors.grey,
                  scaleFactor: 200),
              padding: EdgeInsets.zero,
              margin: EdgeInsets.zero,
              continuousWaveform: true,
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by Ujas-Majithiya** [comment]
@jdevp `startPlayer` has the parameter `finishMode` which you can use to change behaviour when audio ends playing. For your use case, you may use `FinishMode.pause`. See its [documentation](https://pub.dev/documentation/audio_waveforms/latest/audio_waveforms/FinishMode.html)  for more info.

**Comment by ebwood** [comment]
> @jdevp `startPlayer` has the parameter `finishMode` which you can use to change behaviour when audio ends playing. For your use case, you may use `FinishMode.pause`. See its [documentation](https://pub.dev/documentation/audio_waveforms/latest/audio_waveforms/FinishMode.html) for more info.

FinishMode.pause can work for same audio file, but if i reuse the PlayerController for different file, FinishMode.pause is not working in android. iOS is no such problem.

**Comment by Ujas-Majithiya** [comment]
Reopening for further investigation

**Comment by ysgy1121** [comment]
`fun preparePlayer(
        result: MethodChannel.Result,
        path: String?,
        volume: Float?,
        frequency: Long?,
    ) {
        if (path != null) {
            frequency?.let {
                updateFrequency = it
            }
            val uri = Uri.parse(path)
            val mediaItem = MediaItem.fromUri(uri)
            player = ExoPlayer.Builder(appContext).build()
            player?.addMediaItem(mediaItem)
            player?.prepare()
            playerListener = object : Player.Listener {
                override fun onPlayerStateChanged(isReady: Boolean, state: Int) {
                    if (!isPlayerPrepared) {
                        if (state == Player.STATE_READY) {
                            player?.volume = volume ?: 1F
                            isPlayerPrepared = true
                            result.success(true)
                        }
                    }
                    if (state == Player.STATE_ENDED) {
                        val args: MutableMap<String, Any?> = HashMap()
                        when (finishMode) {
                            FinishMode.Loop -> {
                                player?.seekTo(0)
                                player?.play()
                                args[Constants.finishType] = 0
                            }
                            FinishMode.Pause -> {
                                player?.seekTo(0)
                                player?.playWhenReady = false
                                stopListening()
                                args[Constants.finishType] = 1
                            }
                            else -> {
                                player?.stop()
                                player?.release()
                                player = null
                                **isPlayerPrepared = false**
                                stopListening()
                                args[Constants.finishType] = 2
                            }
                        }
                        args[Constants.playerKey] = key
                        methodChannel.invokeMethod(
                            Constants.onDidFinishPlayingAudio,
                            args
                        )
                    }
                }
            }
            player?.addListener(playerListener!!)
        } else {
            result.error(Constants.LOG_TAG, "path to audio file or unique key can't be null", "")
        }
    }`
    
I encountered the same issue while finishMode was set to stop, and I resolved the problem by modifying the code as described.

**Comment by igorfastronicorrea** [comment]
same problem, my state is stopped e when I try .startPlayer() sound not play.

**Comment by jay-simformsolutions** [comment]
> FinishMode.pause can play again for same audio file, but if i reuse the PlayerController for different file, FinishMode.pause is not working in android. iOS is no such problem.

@ebwood, if you want to use PlayerController in a different file, you need to create and use a new player controller in that file.
