### ISSUE TITLE
Most recording formats broken, all others record as m4a on Android and iOS

### ISSUE THREAD

**Issue by jt274** [SimformSolutionsPvtLtd/audio_waveforms#298]
**Describe the bug**
Many of the provided encoder options fail to record. Most that do record do not actually record in the specified format. The `path` and all other parameters were left blank to let the plugin set the path and file extension.

**On iOS**
- `kAudioFormatMPEG4AAC`: Records with `.m4a` extension
- `kAudioFormatMPEGLayer1`: Records with `.m4a` extension
- `kAudioFormatMPEGLayer2`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatMPEGLayer3`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatMPEG4AAC_ELD`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatMPEG4AAC_HE`: Records with `.m4a` extension
- `kAudioFormatOpus`: Records with `.m4a` extension
- `kAudioFormatAMR`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatAMR_WB`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatLinearPCM`: `Failed to start recording, The operation couldn't be completed. (OSStatus error 1718449215.)`
- `kAudioFormatAppleLossless`: Records with `.m4a` extension
- `kAudioFormatMPEG4AAC_HE_V2`: Records with `.m4a` extension

**On Android**
- `aac`: Records with `.m4a` extension
- `aac_eld`: Records with `.m4a` extension
- `amr_nb`: Records with `.m4a` extension
- `amr_wb`: Records with `.m4a` extension
- `he_aac`: Records with `.m4a` extension
- `opus`: Records with `.m4a` extension
- `vorbis`: `Failed to start recording`

**To Reproduce**
```
await controller.record(
  androidEncoder: AndroidEncoder.FORMAT_HERE,
  iosEncoder: IosEncoder.FORMAT_HERE,
);
```

**Expected behavior**
Audio should record in the specified format and with the proper file extension for the format specified.

**Smartphone (please complete the following information):**
- Device: iPhone 11 physical device, iOS 17.4.1
- Device: Pixel 8 Pro API 34 emulator
- `audio_waveforms`: `1.0.5`

**Comment by Ujas-Majithiya** [comment]
@jt274 If you don't provide path in the parameter then it will always record in .m4a format. It is hard coded. If you are changing the encoder then you have set the file format.

If you want specific output format then you may refer to its documentation and check which ender supports it.

**Comment by jt274** [comment]
@Ujas-Majithiya I believe the file extension should be set automatically based on the encoder that is set, rather than to default to .m4a.

What about all of the formats that will not record? If there is a certain file extension or parameters required for those formats to work it should be listed in the documentation.

**Comment by Ujas-Majithiya** [comment]
@jt274 This package is more focused towards waveforms, if enough people require this we may work on this, but currently this is not what we will work on. We are also open to contributions and will love to have yours.
