### ISSUE TITLE
Play button and waveform bugged behavior in Flutter 3.22

### ISSUE THREAD

**Issue by alguintu** [SimformSolutionsPvtLtd/audio_waveforms#299]
**Describe the bug**
The play button and waveform are behaving weirdly in Flutter 3.22. The play buttons are missing, and some waveforms disappear when other audio in the same app are playing.

**To Reproduce**
1. Build example project using Flutter 3.22
2. Run app in release mode
3. See weird behavior of play buttons and waveforms 

**Expected behavior**
The play buttons should behave normally like it does on < 3.22 Flutter versions

**Smartphone (please complete the following information):**
- All emulators/devices we tested on have the same behavior

**Screenshots**
Broken behavior: built on Flutter 3.22

https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/6581480/ebfdb702-ceb3-4146-930d-c1fec378fe6c

Normal behavior: built on Flutter 3.19

https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/6581480/9a70d412-d698-44ec-99e7-f1c0342b57c7

**Additional context**
Experienced these first on our own apps, so we tested rolling back our Flutter version to track.

**Comment by ujas-m-simformsolutions** [comment]
We have just released `1.1.0` which should fix this issue. But if you still facing this issue then feel free to create a new one.
