### ISSUE TITLE
Cannot catch error of preparePlayer

### ISSUE THREAD

**Issue by jt274** [SimformSolutionsPvtLtd/audio_waveforms#301]
**Describe the bug**
When an error is thrown by `controller.preparePlayer`, it cannot be caught. Experiencing this on Android, have not tested on iOS.

For example, when trying to play a file in an invalid format on Android, the console shows the error:

```
Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error
```

However, a try/catch block or `catchError` does not fire, and the code is blocked without further execution.

**To Reproduce**
1. Run `controller.preparePlayer` using an invalid file
2. Try to catch error using `catchError` or try/catch block.
3. Catch does not work

**Expected behavior**
Catch should catch any player errors and continue code execution.

**Comment by dev3-tech** [comment]
yes i faced same thing while controller.preparePlayer

**Comment by toyfind** [comment]
how can i fix PlatformException (PlatformException(AudioWaveforms, Source error, Unable to load media source., null))...however i save the file with .m4a or .mp3
