### ISSUE TITLE
Player waveform doesn't work correctly

### ISSUE THREAD

**Issue by feykro** [SimformSolutionsPvtLtd/audio_waveforms#302]
**Describe the bug**
When using the waveform player, the sounds plays but the waveform doesn't animate correctly and the controller doesn't work, it cannot be stopped.

**To Reproduce**
1. Create a page 1, add a Recorder and record something
2. Create a page 2 that lists the app's audio file
3. Create a modal when you click on the file, in that modal add a Player waveform with the associated file
4. Bug occurs when trying to play the file

**Expected behavior**
The file should play with the waveform showing progress normally. Playback should be pausable.

**Smartphone (please complete the following information):**
- Device: Android Studio simulator, OnePlus 6 
- OS: Android
- Version API 33 for the virtual device, Android 11 for the OP6

**Screenshots**
[Here is a video](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/57326877/c113a427-5b77-4551-ad10-d5bf43b1fcf5)

**Additional context**
On top of that, I have this wall of error text when the playback modal shows up.
<details open>
<summary>Detailed logs</summary>
I/ExoPlayerImpl(29614): Init 496887a [ExoPlayerLib/2.17.1] [emu64a, sdk_gphone64_arm64, Google, 33]
W/mple.reatgistre(29614): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
D/EGL_emulation(29614): app_time_stats: avg=8.32ms min=2.74ms max=105.02ms count=55
I/DMCodecAdapterFactory(29614): Creating an asynchronous MediaCodec adapter for track type audio
D/CCodec  (29614): allocate(c2.android.aac.decoder)
I/Codec2Client(29614): Available Codec2 services: "default" "software"
I/CCodec  (29614): setting up 'default' as default (vendor) store
I/CCodec  (29614): Created component [c2.android.aac.decoder]
D/CCodecConfig(29614): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig(29614): c2 config diff is Dict {
D/CCodecConfig(29614):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(29614):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(29614):   c2::u32 coded.pl.level = 0
D/CCodecConfig(29614):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(29614):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(29614):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(29614):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(29614):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(29614):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(29614):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(29614):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(29614):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(29614):   c2::u32 input.delay.value = 0
D/CCodecConfig(29614):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(29614):   c2::u32 output.delay.value = 2
D/CCodecConfig(29614):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(29614):   string output.media-type.value = "audio/raw"
D/CCodecConfig(29614):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(29614):   c2::u32 raw.channel-mask.value = 0
D/CCodecConfig(29614):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(29614):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(29614): }
I/MediaCodec(29614): MediaCodec will operate in async mode
D/CCodec  (29614): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(29614): no c2 equivalents for flags
D/CCodecConfig(29614): config failed => CORRUPTED
D/CCodecConfig(29614): c2 config diff is   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client(29614): query -- param skipped: index = 1107298332.
D/CCodec  (29614): client requested max input size 412, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (29614): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (29614): encoding statistics level = 0
D/CCodec  (29614): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t bitrate = 64000
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t level = 0
D/CCodec  (29614):   int32_t max-input-size = 8192
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/mp4a-latm"
D/CCodec  (29614):   int32_t profile = 2
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614): }
D/CCodec  (29614): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-drc-output-loudness = -1
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/raw"
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614):   int32_t android._config-pcm-encoding = 2
D/CCodec  (29614): }
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
D/MediaCodec(29614): keep callback message for reclaim
W/Codec2Client(29614): query -- param skipped: index = 1342179345.
W/Codec2Client(29614): query -- param skipped: index = 2415921170.
W/Codec2Client(29614): query -- param skipped: index = 1610614798.
D/C2Store (29614): Using DMABUF Heaps
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#571] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel(29614): [c2.android.aac.decoder#571] Created output block pool with allocatorID 16 => poolID 178 - OK
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#571] Configured output block pool ids 178 => OK
I/DMABUFHEAPS(29614): Using DMA-BUF heap named: system
D/MediaCodecList(29614): codecHandlesFormat: no format, so no extra checks
D/CCodec  (29614): allocate(c2.android.aac.decoder)
I/CCodec  (29614): setting up 'default' as default (vendor) store
I/CCodec  (29614): Created component [c2.android.aac.decoder]
D/CCodecConfig(29614): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig(29614): c2 config diff is Dict {
D/CCodecConfig(29614):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(29614):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(29614):   c2::u32 coded.pl.level = 0
D/CCodecConfig(29614):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(29614):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(29614):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(29614):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(29614):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(29614):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(29614):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(29614):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(29614):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(29614):   c2::u32 input.delay.value = 0
D/CCodecConfig(29614):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(29614):   c2::u32 output.delay.value = 2
D/CCodecConfig(29614):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(29614):   string output.media-type.value = "audio/raw"
D/CCodecConfig(29614):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(29614):   c2::u32 raw.channel-mask.value = 0
D/CCodecConfig(29614):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(29614):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(29614): }
D/CCodec  (29614): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(29614): no c2 equivalents for track-id
D/CCodecConfig(29614): no c2 equivalents for durationUs
D/CCodecConfig(29614): no c2 equivalents for language
D/CCodecConfig(29614): no c2 equivalents for flags
D/CCodecConfig(29614): config failed => CORRUPTED
D/CCodecConfig(29614): c2 config diff is   c2::u32 coded.bitrate.value = 96000
D/CCodecConfig(29614):   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client(29614): query -- param skipped: index = 1107298332.
D/CCodec  (29614): client requested max input size 402, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (29614): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (29614): encoding statistics level = 0
D/CCodec  (29614): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t bitrate = 96000
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t level = 0
D/CCodec  (29614):   int32_t max-input-size = 8192
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/mp4a-latm"
D/CCodec  (29614):   int32_t profile = 2
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614): }
D/CCodec  (29614): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-drc-output-loudness = -1
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/raw"
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614):   int32_t android._config-pcm-encoding = 2
D/CCodec  (29614): }
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
I/MediaCodec(29614): MediaCodec will operate in async mode
D/MediaCodec(29614): keep callback message for reclaim
W/Codec2Client(29614): query -- param skipped: index = 1342179345.
W/Codec2Client(29614): query -- param skipped: index = 2415921170.
W/Codec2Client(29614): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#937] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
I/CCodecBufferChannel(29614): [c2.android.aac.decoder#937] Created output block pool with allocatorID 16 => poolID 179 - OK
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#937] Configured output block pool ids 179 => OK
D/CCodecConfig(29614): c2 config diff is   c2::u32 raw.channel-mask.value = 4
D/CCodecBuffers(29614): [c2.android.aac.decoder#937:Output[N]] popFromStashAndRegister: at 0us, output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(29614):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(29614):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(29614):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(29614):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(29614):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(29614):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(29614):   int32_t channel-count = 1
D/CCodecBuffers(29614):   int32_t channel-mask = 4
D/CCodecBuffers(29614):   int32_t max-output-channel-count = 8
D/CCodecBuffers(29614):   string mime = "audio/raw"
D/CCodecBuffers(29614):   int32_t sample-rate = 48000
D/CCodecBuffers(29614):   int32_t android._config-pcm-encoding = 2
D/CCodecBuffers(29614): }
I/ExoPlayerImpl(29614): Init 4776f64 [ExoPlayerLib/2.17.1] [emu64a, sdk_gphone64_arm64, Google, 33]
I/DMCodecAdapterFactory(29614): Creating an asynchronous MediaCodec adapter for track type audio
D/CCodec  (29614): allocate(c2.android.aac.decoder)
I/CCodec  (29614): setting up 'default' as default (vendor) store
I/CCodec  (29614): Created component [c2.android.aac.decoder]
D/CCodecConfig(29614): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(29614): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig(29614): c2 config diff is Dict {
D/CCodecConfig(29614):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(29614):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(29614):   c2::u32 coded.pl.level = 0
D/CCodecConfig(29614):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(29614):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(29614):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(29614):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(29614):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(29614):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(29614):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(29614):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(29614):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(29614):   c2::u32 input.delay.value = 0
D/CCodecConfig(29614):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(29614):   c2::u32 output.delay.value = 2
D/CCodecConfig(29614):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(29614):   string output.media-type.value = "audio/raw"
D/CCodecConfig(29614):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(29614):   c2::u32 raw.channel-mask.value = 0
D/CCodecConfig(29614):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(29614):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(29614): }
I/MediaCodec(29614): MediaCodec will operate in async mode
D/CCodec  (29614): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(29614): no c2 equivalents for flags
D/CCodecConfig(29614): config failed => CORRUPTED
D/CCodecConfig(29614): c2 config diff is   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client(29614): query -- param skipped: index = 1107298332.
D/CCodec  (29614): client requested max input size 412, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (29614): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (29614): encoding statistics level = 0
D/CCodec  (29614): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t bitrate = 64000
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t level = 0
D/CCodec  (29614):   int32_t max-input-size = 8192
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/mp4a-latm"
D/CCodec  (29614):   int32_t profile = 2
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614): }
D/CCodec  (29614): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (29614):   int32_t aac-drc-album-mode = 0
D/CCodec  (29614):   int32_t aac-drc-boost-level = 127
D/CCodec  (29614):   int32_t aac-drc-cut-level = 127
D/CCodec  (29614):   int32_t aac-drc-effect-type = 3
D/CCodec  (29614):   int32_t aac-drc-output-loudness = -1
D/CCodec  (29614):   int32_t aac-encoded-target-level = -1
D/CCodec  (29614):   int32_t aac-max-output-channel_count = 8
D/CCodec  (29614):   int32_t aac-target-ref-level = 64
D/CCodec  (29614):   int32_t channel-count = 1
D/CCodec  (29614):   int32_t channel-mask = 0
D/CCodec  (29614):   int32_t max-output-channel-count = 8
D/CCodec  (29614):   string mime = "audio/raw"
D/CCodec  (29614):   int32_t sample-rate = 48000
D/CCodec  (29614):   int32_t android._config-pcm-encoding = 2
D/CCodec  (29614): }
I/CCodecConfig(29614): query failed after returning 20 values (BAD_INDEX)
D/MediaCodec(29614): keep callback message for reclaim
W/Codec2Client(29614): query -- param skipped: index = 1342179345.
W/Codec2Client(29614): query -- param skipped: index = 2415921170.
W/Codec2Client(29614): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#780] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
I/CCodecBufferChannel(29614): [c2.android.aac.decoder#780] Created output block pool with allocatorID 16 => poolID 180 - OK
D/CCodecBufferChannel(29614): [c2.android.aac.decoder#780] Configured output block pool ids 180 => OK
D/EGL_emulation(29614): app_time_stats: avg=15.81ms min=4.45ms max=53.51ms count=58
D/CCodecConfig(29614): c2 config diff is   c2::u32 raw.channel-mask.value = 4
D/CCodecBuffers(29614): [c2.android.aac.decoder#571:Output[N]] popFromStashAndRegister: at 1000000000000us, output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(29614):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(29614):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(29614):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(29614):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(29614):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(29614):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(29614):   int32_t channel-count = 1
D/CCodecBuffers(29614):   int32_t channel-mask = 4
D/CCodecBuffers(29614):   int32_t max-output-channel-count = 8
D/CCodecBuffers(29614):   string mime = "audio/raw"
D/CCodecBuffers(29614):   int32_t sample-rate = 48000
D/CCodecBuffers(29614):   int32_t android._config-pcm-encoding = 2
D/CCodecBuffers(29614): }
D/CCodecConfig(29614): c2 config diff is   c2::u32 raw.channel-mask.value = 4
D/CCodecBuffers(29614): [c2.android.aac.decoder#780:Output[N]] popFromStashAndRegister: at 1000000000000us, output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(29614):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(29614):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(29614):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(29614):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(29614):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(29614):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(29614):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(29614):   int32_t channel-count = 1
D/CCodecBuffers(29614):   int32_t channel-mask = 4
D/CCodecBuffers(29614):   int32_t max-output-channel-count = 8
D/CCodecBuffers(29614):   string mime = "audio/raw"
D/CCodecBuffers(29614):   int32_t sample-rate = 48000
D/CCodecBuffers(29614):   int32_t android._config-pcm-encoding = 2
D/CCodecBuffers(29614): }
D/EGL_emulation(29614): app_time_stats: avg=16.62ms min=13.29ms max=19.85ms count=61
D/EGL_emulation(29614): app_time_stats: avg=16.95ms min=11.07ms max=33.27ms count=59
D/EGL_emulation(29614): app_time_stats: avg=16.64ms min=12.92ms max=21.63ms count=61
D/EGL_emulation(29614): app_time_stats: avg=16.66ms min=15.03ms max=18.61ms count=60
D/BufferPoolAccessor2.0(29614): bufferpool2 0xb400007c44f2e418 : 5(40960 size) total buffers - 4(32768 size) used buffers - 16/22 (recycle/alloc) - 12/19 (fetch/transfer)
D/EGL_emulation(29614): app_time_stats: avg=16.66ms min=13.66ms max=19.84ms count=60
D/BufferPoolAccessor2.0(29614): bufferpool2 0xb400007c44ede9e8 : 2(16384 size) total buffers - 2(16384 size) used buffers - 191/196 (recycle/alloc) - 5/193 (fetch/transfer)
D/BufferPoolAccessor2.0(29614): evictor expired: 1, evicted: 1
D/BufferPoolAccessor2.0(29614): bufferpool2 0xb400007c44f601e8 : 5(40960 size) total buffers - 1(8192 size) used buffers - 18/23 (recycle/alloc) - 15/23 (fetch/transfer)
D/EGL_emulation(29614): app_time_stats: avg=16.67ms min=14.08ms max=19.14ms count=61
D/EGL_emulation(29614): app_time_stats: avg=16.63ms min=12.57ms max=20.47ms count=61
D/EGL_emulation(29614): app_time_stats: avg=16.94ms min=13.31ms max=32.03ms count=59
D/EGL_emulation(29614): app_time_stats: avg=16.67ms min=9.93ms max=20.92ms count=60
D/EGL_emulation(29614): app_time_stats: avg=16.64ms min=13.35ms max=19.89ms count=61
D/BufferPoolAccessor2.0(29614): bufferpool2 0xb400007c44f2e418 : 5(40960 size) total buffers - 0(0 size) used buffers - 17/23 (recycle/alloc) - 17/23 (fetch/transfer)
D/BufferPoolAccessor2.0(29614): evictor expired: 2, evicted: 2
</details>

**Comment by deswif** [comment]
same issue

**Comment by jay-simformsolutions** [comment]
Hi @feykro ,

I attempted to reproduce the issue but was unable to replicate it. I’ve attached a video for your review. If you notice anything specific, please let us know so we can investigate further in that direction.

Additionally, could you please share your Flutter version or the output of Flutter Doctor? This might help us diagnose the issue better.

**Testing Device:**
Physical -  Samsung S20 FE
Emulator - Pixel 6




https://github.com/user-attachments/assets/d1603048-de94-4518-bb05-b3552c14c503
