### ISSUE TITLE
visibility issue, waveform not rendered after pause.

### ISSUE THREAD

**Issue by Kamoba** [SimformSolutionsPvtLtd/audio_waveforms#316]
Using Player, after ```preparePlayer``` i play with  ```await audioPlayerController.startPlayer(finishMode: FinishMode.pause); ```
Then use the widget:
```
                  if(isPlaying)
                      AudioFileWaveforms(
                      size: Size(MediaQuery.of(context).size.width, 30.0),
                      playerController: audioPlayerController,
                      enableSeekGesture: true,
                      waveformType: WaveformType.fitWidth,
                      waveformData: const [],
                      playerWaveStyle: const PlayerWaveStyle(
                        fixedWaveColor: Colors.white54,
                        liveWaveColor: Colors.blueAccent,
                        showSeekLine: false,
                        spacing: 6,
                        ),
                      ),
```
The waveform will show normally.

Now I do pause using ```await audioPlayerController.pausePlayer();``` then set isPlaying to false.
But when resume with set isPlaying to true and play again with ```await audioPlayerController.startPlayer(finishMode: FinishMode.pause); ``` I do not see the waveform anymore. 

I made multo test to check if come from somewhere else like **isPlaying**, but no, it's come from the fact **AudioFileWaveforms** do not pick-up the waveformData when from paused to playing state.

So in my case I just use opacity as solution:
```
                    Opacity(       
                    opacity: isPlaying? 1.0 : 0.0,
                    child: AudioFileWaveforms(
                        size: Size(MediaQuery.of(context).size.width, 30.0),
                        playerController: audioPlayerController,
                        enableSeekGesture: true,
                        waveformType: WaveformType.fitWidth,
                        waveformData: const [],
                        playerWaveStyle: const PlayerWaveStyle(
                          fixedWaveColor: Colors.white54,
                          liveWaveColor: Colors.blueAccent,
                          showSeekLine: false,
                          spacing: 6,
                          ),
                        ),
                      ),
```

I just report this issue because seam to me important to fix.

I use Android emulator, audio_waveforms  last version and  Flutter  3.22.2.

**Comment by ujas-m-simformsolutions** [comment]
@Kamoba Thanks for the report. All variables initialisation is done in the initstate and when you hide and then unhide the widget initState is not being called again so it is not showing waveforms again.

**Comment by himanshuGandhiSimform** [comment]
Hello, @Kamoba if you are extracting the data, then you can directly pass it on to AudioFileWaveforms, but make sure you check the extract progress it must be > 1.0.
`if (isPlaying)
                    AudioFileWaveforms(
                      size: Size(MediaQuery.of(context).size.width / 2, 70),
                      playerController: controller,
                      enableSeekGesture: true,
                      waveformType: WaveformType.fitWidth,
                      waveformData: progess >= 1.0 ? _waveformData : [],
                      playerWaveStyle: const PlayerWaveStyle(
                        fixedWaveColor: Colors.white54,
                        liveWaveColor: Colors.blueAccent,
                        showSeekLine: false,
                        spacing: 6,
                      ),
                    ),`

**Comment by Kamoba** [comment]
@himanshuGandhiSimform thank you for your contribution. After testing and learning this package, I improved my code by storing the extracted waveform as you suggested with one small difference: I use a variable ```acceptableWaveFormLength = noOfSamples>2? (noOfSamples -2) : 0;```

Reason: onExtractionProgress doesn't work for me, I think I reported this problem on another Issue ticket, and sometimes the extraction isn't complete so I ignore them (not saved) then extract again on the next read.
