### ISSUE TITLE
Save waveform after preparePlayer

### ISSUE THREAD

**Issue by Kamoba** [SimformSolutionsPvtLtd/audio_waveforms#318]
Playing of certain audio files lasting at least 2 minutes, you'll notice that the data is generated asynchronously, "in waves", one by one, like you said somewhere it can be slow for Android. If it has to be replayed more than once, there will be redundancy. An option to save it and display it next time would be appreciated.

**Comment by ujas-m-simformsolutions** [comment]
@Kamoba You can use `PlayerController().extractWaveformData` to extract waveform data and save it and now when you need to show waveform again just directly provide data to waveform widget. Also just set false to `shouldExtractWaveform` in preparePlayer.
