### ISSUE TITLE
Recorder controller returns the path when paused 

### ISSUE THREAD

**Issue by tsgofficial** [SimformSolutionsPvtLtd/audio_waveforms#322]
Can RecorderController.pause() save the current recorded audio and return the path just like RecorderController.stop(). I need this feature in my application where it would be able to play the currently recorded audio (with RecorderController.pause()) with PlayerController.

**Comment by Anikets08** [comment]
I had same requirement, I used to stop the audio and once user is satisfied I merge the audio using ffmpeg

**Comment by jay-simformsolutions** [comment]
Duplicate #208
