### ISSUE TITLE
Play audio not working in Android in release mode

### ISSUE THREAD

**Issue by mu7mmd** [SimformSolutionsPvtLtd/audio_waveforms#326]
**Smartphone:**
- Device: Samsung s21 ultra
- OS: Android 13
- Version: One UI 5.1

**Additional context**
audio_waveforms version: 1.0.5

**Comment by shoxrux06** [comment]
same issue

**Comment by dileep-kumar12** [comment]
same issue

**Comment by daman78880** [comment]
You must cancel all streams and dispose of all controllers of the wave; after that, it will work for you.

**Comment by mu7mmd** [comment]
After researching the problem, I identified that the issue lies within Flutter version 3.22. Consequently, I decided to downgrade my version to 3.19, and the application now operates without any issues. I am optimistic that the matter will be addressed in forthcoming releases :(

**Comment by ujas-m-simformsolutions** [comment]
Should be fixed in latest release `1.1.0`
