### ISSUE TITLE
can't import RecorderController in "import 'package:audio_waveforms/audio_waveforms.dart'"

### ISSUE THREAD

**Issue by 99gony** [SimformSolutionsPvtLtd/audio_waveforms#33]
There's only WaveController exist.
Can I use WaveController instead of RecorderController?

**Comment by 99gony** [comment]
sorry, I first see github repository instead of pub.dev.

**Comment by ujas-m-simformsolutions** [comment]
Hey @99gony we have released the new version you can you use that from now.

**Comment by 99gony** [comment]
> 
Thank you!
This package is awesome.
