### ISSUE TITLE
PlatformException(AudioWaveforms, Failed to prepare player, The operation couldn’t be completed. (OSStatus error 2003334207.), null)

### ISSUE THREAD

**Issue by abbasihamed** [SimformSolutionsPvtLtd/audio_waveforms#337]
**Describe the bug**
In ios, when the file address is given online, I get the following error

PlatformException(AudioWaveforms, Failed to prepare player, The operation couldn’t be completed. (OSStatus error 2003334207.), null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      AudioWaveformsInterface.preparePlayer (package:audio_waveforms/src/base/audio_waveforms_interface.dart:100:18)
<asynchronous suspension>
#3      PlayerController.preparePlayer (package:audio_waveforms/src/controllers/player_controller.dart:122:24)
<asynchronous suspension>

**This item works properly on Android**

This is my code
```
  final PlayerController controller = PlayerController();
    controller.preparePlayer(
      path: "url",
      shouldExtractWaveform: true,
    );

```

**Smartphone (please complete the following information):**
- Device: [e.g. IPhone 15 pro max]
- OS: [e.g. iOS17]

**Comment by XCarlosEduardoX** [comment]
same :C

**Comment by abbasihamed** [comment]
> same :C

Did you find a solution for it?

**Comment by XCarlosEduardoX** [comment]
> > same :C
> 
> Did you find a solution for it?

nop, I have an error in PlayerController.preparePlayer, when playing the audio it shows me this error: playback error

**Comment by Hvt261** [comment]
Same problem when file is large than 3mb

**Comment by Hvt261** [comment]
With small file, it work normally. It happen on ios only

**Comment by AtharvaChavan04** [comment]
@Hvt261 , how are you able to run small file , i am trying to run a 1mb mp3 file, that too is giving the same error.

**Comment by Hvt261** [comment]
You should download and play the local file path

**Comment by boyallex** [comment]
Same problem
it does not depend on file, same file can open and break, problem in player on IOS (only)
Has anyone found a solution?

**Comment by prazeev** [comment]
Any solutions yet?

**Comment by Hvt261** [comment]
Download file with extension .wav 
work normally on both android and ios

**Comment by Hvt261** [comment]
final file = await _downloadFile(widget.soundPath, 'download.wav');
 await _playerController.preparePlayer(path: file.path);
 
 Future<File> _downloadFile(String url, String filename) async {
    try {
      final response = await http.get(Uri.parse(url));
      if (response.statusCode == 200) {
        final directory = await getTemporaryDirectory();
        final file = File('${directory.path}/$filename');
        return file.writeAsBytes(response.bodyBytes);
      } else {
        throw Exception('Failed to load file');
      }
    } catch (e) {
      throw Exception('Error downloading file: $e');
    }
  }

**Comment by rickybrown** [comment]
I got it to work by using `flutter_cache_manager`

```
import 'package:flutter_cache_manager/flutter_cache_manager.dart';

...

try {
  var fileInfo = await DefaultCacheManager().getSingleFile(widget.url);
  cachedFilePath = fileInfo.path;

  // Prepare the player with the local file
  await _playerController.preparePlayer(
    path: cachedFilePath!,
    shouldExtractWaveform: true,
    noOfSamples: 100,
  );
} catch (e) {
  print("Error preparing player: $e");
}

```

Very easy :)

**Comment by ujas-m-simformsolutions** [comment]
@abbasihamed We currently do not support remote audio so first you will need to download it and then you will be able to play it and show waveform.

**Comment by Alllaa** [comment]
> I got it to work by using `flutter_cache_manager`
> 
> ```
> import 'package:flutter_cache_manager/flutter_cache_manager.dart';
> 
> ...
> 
> try {
>   var fileInfo = await DefaultCacheManager().getSingleFile(widget.url);
>   cachedFilePath = fileInfo.path;
> 
>   // Prepare the player with the local file
>   await _playerController.preparePlayer(
>     path: cachedFilePath!,
>     shouldExtractWaveform: true,
>     noOfSamples: 100,
>   );
> } catch (e) {
>   print("Error preparing player: $e");
> }
> ```
> 
> Very easy :)

THX
