### ISSUE TITLE
Problem with "enhanced-enums"

### ISSUE THREAD

**Issue by MHD-Saleh** [SimformSolutionsPvtLtd/audio_waveforms#340]
The **audio_waveforms** package currently specifies a minimum **SDK** version of 2.12.0, which is below the minimum required for using enhanced **enums** (2.17 or higher). This incompatibility prevents users from utilizing the **enhanced-enums** feature within this package.

**To Reproduce**

1. Install the audio_waveforms package:
  audio_waveforms:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/audio_waveforms.git
      ref: main
2. run it with flutter 3.22 and dart 3.4.1
3.The following error will be encountered:
![image](https://github.com/user-attachments/assets/fce0c5e0-83b9-47aa-9179-02b59f8ec8ba)

error gets from here:

![image](https://github.com/user-attachments/assets/eec8d0f4-0ad4-497c-b1d7-92e5731617e9)

**Expected behavior**
The package should be compatible with the latest language features, including enhanced enums. Users should be able to utilize these features without encountering errors.

**Possible Solutions:**

Update the minimum SDK version: Modify the sdk constraint in the package's pubspec.yaml file to sdk: ">=2.17.0 <4.0.0".
Provide an alternative: If updating the SDK version is not feasible, consider providing an alternative approach or workaround for users who need to use enhanced enums.

Edit 1 :
i use the main Version because i have problem shows only in release version Which is all instance shared same Key 
Mentioned in #303

**Comment by ujas-m-simformsolutions** [comment]
@MHD-Saleh Thank you for creating this issue and the PR. We have just released 1.1.0 with higher minimum flutter version so this should resolve your issue.
