### ISSUE TITLE
Need a callback when dragging the waveform while player is stopped 

### ISSUE THREAD

**Issue by novas1r1** [SimformSolutionsPvtLtd/audio_waveforms#342]
Hey, 
first of all thank you very much for this package and the work you put in :)!

**Is your feature request related to a problem? Please describe.**
I added an audio player which plays a local mp3 file. I'm visualizing the waveforms and when I'm playing the audio file and dragging it to another position, the player jumps correctly and continues playing from this position. But when I stop the player, drag to a position and start the player again, it does not continue playing from the position where I dragged it but from where it was first stopped. 

**Describe the solution you'd like**
This could be solved by having a callback when dragging the waveform so I could just use the seek for the player and set it to the according position.

**Describe alternatives you've considered**
Alternatively it could set the player position within the package automatically when the waveform is dragged to a specific position.

**Additional context**
Maybe this is already possible somehow, but I checked documentation and issues and couldnt find anything.

Thanks a lot :)!

**Comment by ujas-m-simformsolutions** [comment]
Hey @novas1r1 thank you for creating this issue, we currently does not have this feature but we have PR which could fix this. We will merge it as soon as possible. Thank you for your patience.

**Comment by robert1979** [comment]
looking forward to this fix.
Thanks!

**Comment by ujas-m-simformsolutions** [comment]
Feature added in 1.2.0.
