### ISSUE TITLE
file path error in playerController

### ISSUE THREAD

**Issue by 99gony** [SimformSolutionsPvtLtd/audio_waveforms#35]
I want to record and then play the file.
Code like this
![Screen Shot 2022-05-03 at 9 15 46 PM](https://user-images.githubusercontent.com/72787759/166451451-ba3e014b-4d55-4a12-bf34-26efee1371cf.png)

But, occur this error.
![Screen Shot 2022-05-03 at 9 16 27 PM](https://user-images.githubusercontent.com/72787759/166451597-bdee2730-3ba4-4cfe-8639-f2e1db9d1ba9.png)

Test in my real device iphone8+.
Is my code wrong?

And I also try in my real android device.
Then no problem.

**Comment by ujas-m-simformsolutions** [comment]
Hey @99gony, Can you try removing `file//:` from beginning of the path and keep only one `/`.

**Comment by 99gony** [comment]
> Hey @99gony, Can you try removing `file//:` from beginning of the path and keep only one `/`. So it would look like `/private/var/mobile/Container...`

I solved. Very Thanks.

I have one more problem I think.
Recording wave sync is good, but playing wave sync is weird.

**Comment by ujas-m-simformsolutions** [comment]
@99gony Did provided solution solved your problem? And can you provide more feedback for playing wave like how should it behave in your perspective so that we can improve the plugin.

**Comment by 99gony** [comment]
> @99gony Did provided solution solved your problem? And can you provide more feedback for playing wave like how should it behave in your perspective so that we can improve the plugin.
re

**Comment by 99gony** [comment]
I just do like this on Ios.
path = await recorderController.stop();
    final p = path!.substring(7);
    print(p);
    await playerController.preparePlayer(p);

And, the playing wave is weird. It looks like Randomly render wave.
I recorded no sound and stop it. (recording wave is good)
But playing wave looks like very activity.
Both android and ios.

**Comment by ujas-m-simformsolutions** [comment]
Thank you for you feedback I will look into this. And closing the as path required just to remove some characters at beginning.

**Comment by 99gony** [comment]
I hope Playing wave is be same recording wave.
And hope playing wave's animation is more softly like recording wave.
