### ISSUE TITLE
add support for webm format

### ISSUE THREAD

**Issue by Rahul7f** [SimformSolutionsPvtLtd/audio_waveforms#352]
I attempted to play an audio file in WEBM format, but encountered the following error:
`Offset argument contained a NaN value.
'dart:ui/painting.dart': 
Failed assertion: line 36 pos 10: '<optimized out>'`

Observations:
	•	Audio playback is functioning as expected.
	•	However, the audio waveform visualization is not rendering.

**Comment by adar2378** [comment]
How this was fixed? It still throws the same error

**Comment by DamanSoftRadixx** [comment]
How to fix this ?

**Comment by ihda06** [comment]
how do you fix this issue ? @Rahul7f
