### ISSUE TITLE
WaveformType.fitWidth only shows about half of the waveform

### ISSUE THREAD

**Issue by UnicornaasTech** [SimformSolutionsPvtLtd/audio_waveforms#355]
**Describe the bug**
Just installed audio_waveforms: 1.1.1 and created a player playing a file produced with recording functionality.

When using AudioFileWaveforms with WaveformType.fitWidth, it only shows about half of the audio waveform - the first half. The playback continues still, but the visualization of the waveform and animation of the playback only shows about until half of the audio. I've tried different sample amounts (I'm generating it with playerWaveStyle.getSamplesForWidth), but the effect remains the same.

When I use WaveformType.long, it works as expected.

**To Reproduce**
I prepare the audio like this:
-----
  int waveFormSamples = playerWaveStyle.getSamplesForWidth(_approxWaveformWidth);
---
  Future<void> startOrStopRecording(int waveFormSamples) async {
    try {
      if (status.value == RecordingStatus.recording) {
        path = await recorderController.stop(false);

        // if stopping succeeded, we got a file path
        if (path != null) {
          logger.d("Recorded file size: ${File(path!).lengthSync()}");
          // Prepare player to play the file
          await player.prepare(path!, waveFormSamples);
          // reset the wave out
          recorderController.reset();
          // This will trigger UI to react
          status.value = RecordingStatus.recordingCompleted;
-----

Use widget like this:
-----
AudioFileWaveforms(
              continuousWaveform: true,
              size: const Size(_approxWaveformWidth, _waveformHeight),
              playerController: widget.controller,
              enableSeekGesture: true,
              waveformType: WaveformType.fitWidth,
              playerWaveStyle: PlayerWaveform.playerWaveStyle
            )
----

**Expected behavior**
Should show the waveform for the entire span of the audio.

**Smartphone (please complete the following information):**
- Device: iPhone 16 simulator, run on OSX

**Screenshots**
![image](https://github.com/user-attachments/assets/08edaca1-c090-4dbe-9fe1-dce57fe7081d)

**Comment by ujas-m-simformsolutions** [comment]
@UnicornaasTech As mentioned in the [docs](https://pub.dev/documentation/audio_waveforms/latest/audio_waveforms/WaveformType.html), when you're using fitWidth, you will need to provide number samples according to your PlayerWaveStyle.
```
final style = PlayerWaveStyle();
playerController.preparePlayer(noOfSamples: style.getSamplesForWidth(width));
```
I'm going to close this issue for now but feel free to reopen it if issue persists.

**Comment by UnicornaasTech** [comment]
Hi,

Thanks, however, please do not close.
I am using exactly that getSamplesForWidth, but the issue persists. Also, I've tried scaling the returned value up and down, but it does not seem to fix the issue - whatever value I use for samples, it always cuts of parts on the right side.

What could I do to support more on sorting this out?

**Comment by cosmopolit** [comment]
Same issue here, but when using the half of the real size value for noOfSamples it scales correctly the visible waveform but not the size for tap and drag area. The area remains twice the size. 
When tapping to the end it selects the middle. Whats wrong here? I dont think its device specific because i have three different test Devices.
