### ISSUE TITLE
Cant build flutter project with audio_waveforms as transitive dependency

### ISSUE THREAD

**Issue by Seeyouinthespring** [SimformSolutionsPvtLtd/audio_waveforms#358]
**Describe the bug**
AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:29:41 Unresolved reference: AudioRecorder
e: AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:37:51 Unresolved reference: WaveformExtractor
e: AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:43:25 Unresolved reference: AudioRecorder
e: AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:258:33 Unresolved reference: WaveformExtractor
e:AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:265:42 Unresolved reference: ExtractorCallBack
e: /AppData/Local/Pub/Cache/hosted/pub.dev/audio_waveforms-1.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt:266:17 'onProgress' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audio_waveforms:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

Here is my flutter doctor

 Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.5011], locale ru-RU)
    • Flutter version 3.24.0 on channel stable at C:\DEVELOPMENT\src\flutter_windows_3.16.9-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\colya\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available)
    • SM N950F (mobile) • 988a1b36314858574730 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows              • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 129.0.2792.65

[√] Network resources
    • All expected network resources are available.

**Comment by ujas-m-simformsolutions** [comment]
@Seeyouinthespring I'm not sure but maybe audio_waveforms dependency isn't properly added. Can you please share your pubspec.yaml? Also, as your title mentions transitive dependency then maybe some other dependencies which uses audio_waveforms is causing this issue.

**Comment by Seeyouinthespring** [comment]
Here is pubspec.yaml from my realization of chatview

name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.3.11
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  emoji_picker_flutter: ^2.1.1
  http: ^1.1.0
  html: ^0.15.1
  any_link_preview: ^3.0.0
  progress_indicators: ^1.0.0
  image_picker: '>=0.8.9 <2.0.0'
  audio_waveforms: ^1.0.1
  # For formatting time locale in message receipts
  timeago: ^3.4.0
  file_picker: ^8.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
___________________________________

and chatview is imported from git in my project

chatview:
    git:
      url: git@git.grotem.com:flutter-libs/chatview.git
      ref: 1.3.11

btw this problems reproduces in chatview example app also. Updating audio_waveforms to the lates version (1.1.1) is not helping

**Comment by ujas-m-simformsolutions** [comment]
@Seeyouinthespring I just cloned the [chatview](https://github.com/SimformSolutionsPvtLtd/flutter_chatview) and I'm able to run the example app. My flutter version is `3.24.3`. Maybe something is wrong with your pub cache. you can try the commands `flutter pub cache clean`, `flutter clean` and also delete the pubspec.lock. This will delete all the cached flutter dependencies.It will re-download dependency for every project next time. Or you can just manually delete that folder.

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue as no further response was provided.
