### ISSUE TITLE
`main` fails to build iOS project

### ISSUE THREAD

**Issue by raulmabe-labhouse** [SimformSolutionsPvtLtd/audio_waveforms#360]
**Describe the bug**
I am using the main version on our project because we need the iOS sound fix. 

The file `SwiftAudioWaveformsPlugin.swift` has some backtick that does not allow the app to be built.

There is one at line 0, and another one at line 180. Removing these backticks fix the issue.

![image](https://github.com/user-attachments/assets/8b740b6c-c6ef-4dbf-97b4-3662bad1b253)

**Comment by ujas-m-simformsolutions** [comment]
This should be fixed now.
