### ISSUE TITLE
The named parameter 'finishMode' isn't defined

### ISSUE THREAD

**Issue by karimi1064** [SimformSolutionsPvtLtd/audio_waveforms#374]
After upgrading the version to `audio_waveforms 1.2.0` I got this error:

The named parameter '`finishMode`' isn't defined

For this part of the code:

```
 onPressed: () async {
                  controller.playerState.isPlaying
                      ? await controller.pausePlayer()
                      : await controller.startPlayer(
                          finishMode: FinishMode.pause,
                        );
                },
```

**Comment by ujas-m-simformsolutions** [comment]
@karimi1064 From 1.2.0, you can set the finish mode from separate function like this,
```
controller.setFinishMode(finishMode: FinishMode.stop);
```

**Comment by karimi1064** [comment]
> @karimi1064 From 1.2.0, you can set the finish mode from separate function like this,
> 
> ```
> controller.setFinishMode(finishMode: FinishMode.stop);
> ```

Thanks @ujas-m-simformsolutions .

**Comment by Mistic92** [comment]
When I use it as separate function my player does not work at all
```
      await audioCtrl.setFinishMode(finishMode: FinishMode.pause);
      await audioCtrl.startPlayer();
 ```
