### ISSUE TITLE
how can I get state when finished?

### ISSUE THREAD

**Issue by srcho** [SimformSolutionsPvtLtd/audio_waveforms#38]
When the player is finished, how can I get state? The controller.stop or pause is not received by the listener. Even when I print out the log, it stops at state.playing.

**Comment by ujas-m-simformsolutions** [comment]
Hey @srcho, A listener for `playerState`  is yet to be implemented.  But  `playerController.playerState` will receive the new state whenever there is a change in playerState. Can you share your code so that we can test it?

**Comment by srcho** [comment]
> Hey @srcho, A listener for `playerState` is yet to be implemented. But `playerController.playerState` will receive the new state whenever there is a change in playerState. Can you share your code so that we can test it?

Thank you for your quick response. What I tested is your example code. Among them, the controller 5 utilizes the recording function. After the recorded file is created and played, the Stop button is activated even if the entire length is played. I just modified the listener a little bit in your example code.

playerController1 = PlayerController()
      ..addListener(() {
        print(playerController1.playerState);
        if (playerController1.playerState == PlayerState.stopped) {
          print('stop');
        }
        if (mounted) setState(() {});
      });

Result log: 
flutter: PlayerState.readingComplete
flutter: PlayerState.initialized
flutter: PlayerState.playing

That log is everything. when the recorded file is finished playing. I have to press the pause button with my hand to play it again.

I want to change the status of isPlaying again automatically after playing the recording file. Or I want to receive PlayerState. stop or pause. Your package is so cool. It's interesting and good, so I leave the question like this. I want to keep using it. Thank you.

**Comment by Ujas-Majithiya** [comment]
Ok sorry I misunderstood at first, I thought after calling `stopPlayer()`, it wasn't getting the state. Anyways, yes it's a bug and I think should also provide a listener for current duration. Ok thank you for reporting this we will soon release a patch for this

**Comment by tonkla500** [comment]
I have this problem too.

**Comment by ujas-m-simformsolutions** [comment]
@tonkla500 you can use `feature/player-state-update` branch as it has patch for this and some new features ,until next the patch gets released.

**Comment by zzterrozz** [comment]
Please push this to `pub.dev` when you have a chance!
