### ISSUE TITLE
Is there a way to add different codec than standard Android? such as encoding in PCM16 

### ISSUE THREAD

**Issue by purelog1c** [SimformSolutionsPvtLtd/audio_waveforms#39]

**Comment by Ujas-Majithiya** [comment]
On the native android side, this plugin is dependent on `MediaRecorder` which doesn't support `pcm16`. To support it, we have to use `AudioRecord`. For now, there are no plans to change the base recorder class. And this plugin is more focused on `Waveforms` with basic recorder/player functionalities.

Right now, we plan to improve this plugin so this won't be worked on near future.

**Comment by ujas-m-simformsolutions** [comment]
closing this issue as for now
