### ISSUE TITLE
After I upgrade flutter 3.0. build error on android

### ISSUE THREAD

**Issue by 99gony** [SimformSolutionsPvtLtd/audio_waveforms#41]
/Users/gony/development/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (20, 1): Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/gony/development/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (97, 5): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audio_waveforms:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

This is error code. How I can fix it?

**Comment by ujas-m-simformsolutions** [comment]
Hey @99gony, This required just to remove `?` from a parameter. I have pushed the update code in this branch [`temp-3.0.0.fix`](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/tree/temp-3.0.0.fix). For now, you can use this by adding git url in pubspec until we update sdk for plugin.

**Comment by abhay-s-rawat** [comment]
I got fix for this

**Comment by abhay-s-rawat** [comment]
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/pull/53

**Comment by zzterrozz** [comment]
Same problem here, why is the PR not merged in the main branch?

**Comment by hatemragab** [comment]
is this fix uploaded to pub dev audio_waveforms: ^0.1.5+1 ?

**Comment by hatemragab** [comment]
please pump the  version on pub dev i need to publish a package depending on this package but i cant because of this bug
and cant publish package from git url
