### ISSUE TITLE
Waveforms of no sound at all appear at their max size instead of their min size 

### ISSUE THREAD

**Issue by noygafni** [SimformSolutionsPvtLtd/audio_waveforms#43]
My code:
```dart
@override
  void initState() {
    super.initState();
    _recorderController = RecorderController();
    _recorderController.record();
  }

...

AudioWaveforms(
    size: const Size(230, 50),
    recorderController: _recorderController,
    waveStyle: const WaveStyle(
      waveColor: Colors.pink,
      spacing: 8.0,
      extendWaveform: true,
      showMiddleLine: false,
   ),
)
```
For some reason the wave forms of absolute silence appear at max size. 
Here is a photo - took the screenshot when there was no sound at all
![no sound bug](https://user-images.githubusercontent.com/48031215/168665308-dd971278-744d-4347-86a2-25056ecec306.png)

It is important to mention that when there is sound the waveforms seems to work as expected.

**Comment by ujas-m-simformsolutions** [comment]
From your this #44 issue I see you are using an emulator. Can you please test it on a real device because android emulators behave weirdly in different scenarios?

**Comment by renankanu** [comment]
Here the same thing happens, I tested it on a real device.

**Comment by renankanu** [comment]
I found the possible cause, in `RecorderWavePainter` the `waveData[i]` is coming a negative value, using this condition the wave worked as it should: `(waveData[i] < 0 ? 0 : waveData[i])`.

**Comment by renankanu** [comment]
Adding this `..normalizationFactor = 40`, works here for me. The default for android is 60.

**Comment by noygafni** [comment]
That seems to improve this, thank you so much

**Comment by noygafni** [comment]
Acutely after a lot of testing setting the `..normalizationFactor = 40` is still not good enough. for some reason the sound waves does not react correctly to my voice. further more when I play the recording using `AudioFileWaveforms` the sound waves look completely different than the sound waves while recording. I think it is a bug.
