### ISSUE TITLE
The last wave form is always flickering when recording

### ISSUE THREAD

**Issue by noygafni** [SimformSolutionsPvtLtd/audio_waveforms#44]
My code:
```dart
@override
  void initState() {
    super.initState();
    _recorderController = RecorderController();
    _recorderController.record();
  }

...

AudioWaveforms(
    size: const Size(230, 50),
    recorderController: _recorderController,
    waveStyle: const WaveStyle(
      waveColor: Colors.pink,
      spacing: 8.0,
      extendWaveform: true,
      showMiddleLine: false,
   ),
)
```
For some reason the last wave form always appears to be flickering:
![recording flickering bug](https://user-images.githubusercontent.com/48031215/168665887-9dcf3e87-26a0-4647-bc98-1eb7b798d8c2.gif)

Is this a bug? or am I doing something wrong?

**Comment by ujas-m-simformsolutions** [comment]
Actually when a wave is generated the first time it just suddenly appears without any animation so that's why it looks flickering. I will put it under bug.

**Comment by marcinFDT** [comment]
I noticed that too, would be glad for fix
