### ISSUE TITLE
Waveforms for extra long audios

### ISSUE THREAD

**Issue by hey-nicolasklein** [SimformSolutionsPvtLtd/audio_waveforms#47]
I'm recording interview sessions, each lasting more than 60 minutes. Displaying the whole waveform is to inaccurate to skim through the interview.

Is there any way to scroll vertically with the audio with the player?
The Audiorecorder does exactly what I want, just that I want a player with that style.

Thanks in advance for any help.

**Comment by ujas-m-simformsolutions** [comment]
The waveforms for the player were primarily focused on chat-like UI with limited space for horizontal seek. We can put it under enhancement for future releases.

**Comment by hey-nicolasklein** [comment]
Thank you, that would be nice. I'm currently working on a version where you vertically scroll a viewport of a specific duration. If that feature would be present in your package, it would really cover all the most important use cases around waveforms.

**Comment by ujas-m-simformsolutions** [comment]
@hey-nicolasklein We have release `1.0.0` to pub.dev with this feature and many more

**Comment by prashanttechnoyuga** [comment]
Hey, @ujas-m-simformsolutions any update on space for long horizontal seek?

**Comment by ujas-m-simformsolutions** [comment]
@prashanttechnoyuga This feature is already released.
