### ISSUE TITLE
Is there a way to listen to player reaching end of audio file?

### ISSUE THREAD

**Issue by noygafni** [SimformSolutionsPvtLtd/audio_waveforms#48]
I am using `AudioFileWaveforms` to listen to an audio recording. I have a play button that turns into a pause button once the recording start. I achieve that using `addListener()` on the `PlayerController` as shown in the docs example. My problem is that I want to turn the pause button back to play button once the player reached the end of the recording. I can see that the listener is not called when the player reaches the end.
I was wondering if maybe there is a way to do this? and if not it could be a good enhancement

**Comment by Technorocker** [comment]
I was just coming to see if this was possible myself.

**Comment by bulgarian-beast** [comment]
Same

**Comment by Ujas-Majithiya** [comment]
@bulgarian-beast Thanks for the temporary solution. 

@noygafni  Now, if you want to listen to player state changes then you can use this stream `playerController.onPlayerStateChanged.listen((state) {});` which will provide any state changes in PlayerController.

Also, we have one new enum `FinishMode` which you can pass in the `startPlayer()` as a parameter. It will provide some level of control when currently playing audio ends. Check its documentation for more info.

**Comment by ujas-m-simformsolutions** [comment]
Closing this as we have two types of streams for listening to PlayerState changes, duration changes, and an enum to control how audio should end. This should cover the use case.
