### ISSUE TITLE
Push to Pub.dev + Flutter 3.0

### ISSUE THREAD

**Issue by zzterrozz** [SimformSolutionsPvtLtd/audio_waveforms#49]
Can you please push the last version to pub.dev + fix the flutter 3.0 warning?

**Comment by zzterrozz** [comment]
@DevarshRanpara , [https://pub.dev/packages/audio_waveforms/changelog](https://pub.dev/packages/audio_waveforms/changelog) is still under version `audio_waveforms: ^0.1.1`

**Comment by DhavalRKansara** [comment]
duplicate of #41
