### ISSUE TITLE
Build Error with Flutter 3

### ISSUE THREAD

**Issue by ehsan097** [SimformSolutionsPvtLtd/audio_waveforms#51]
I upgrade flutter version to 3 then the plugin produces errors like.

audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (20, 1): Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener

e: /Users/user/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (97, 5): 'onRequestPermissionsResult' overrides nothing

kindly guide me how to reslove this issue.
Thanks

**Comment by abellee** [comment]
me too.
