### ISSUE TITLE
Waveform scroll gesture can't begin with swipe to left

### ISSUE THREAD

**Issue by william-herring** [SimformSolutionsPvtLtd/audio_waveforms#52]
I've noticed this strange behaviour where I can only begin with a swipe-right gesture to scroll through the waveform. I can swipe left but only if I begin the gesture with a swipe to the right. Below is the AudioWaveforms widget, let me know if you need the full code snippet. I have also attached a recording of this behaviour.

```dart
AudioWaveforms(
  enableGesture: true,
  size: const Size(double.infinity, 80.0),
  waveStyle: const WaveStyle(
    showMiddleLine: false,
    waveThickness: 4,
  ),
  recorderController: recorderController,
)
```

![image](https://user-images.githubusercontent.com/73984595/172319663-637a8a62-c450-4ed7-a171-cab424132d53.png)

**Comment by Ujas-Majithiya** [comment]
@william-herring Let's say we are allowing left swipe when waveforms are in the initial state. In the initial state, waves are at the middle of the screen if the `extendWaveform` flag is set false else they will be at the start of the viewport at the right side. Now, when you left swipe waves will start going outside of the viewport from the beginning so allowing waves to go outside of the viewport makes sense. 
Do let us know if this clears things up.

**Comment by Ujas-Majithiya** [comment]
And you have provided a image not video
