### ISSUE TITLE
Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult

### ISSUE THREAD

**Issue by hasanmhallak** [SimformSolutionsPvtLtd/audio_waveforms#57]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by premy** [comment]
same here

**Comment by hasanmhallak** [comment]
@premy I add a pull request that fix this issue, you can check that out.
#60

**Comment by han-tm** [comment]
When this pull will merged?

**Comment by devDonald** [comment]
Please who has solved this issue

**Comment by devDonald** [comment]
@hasanmhallak please any help?

**Comment by DhavalRKansara** [comment]
Duplicate of #50
