### ISSUE TITLE
Replay the audio player

### ISSUE THREAD

**Issue by AimanKyo97** [SimformSolutionsPvtLtd/audio_waveforms#64]
How to to replay the audio? 
And how to do function if the audio play is already end?

@tejas-ardeshna  @BirjuVachhani  @DevarshRanpara  @vatsaltanna-simformsolutions  @ujas-m-simformsolutions

**Comment by DhavalRKansara** [comment]
This issue has been fixed, you will find the updates in the next release. For now you can get this plugin direct from the main branch on the Github repository. You just have to set `controller.startPlayer(finishMode: FinishMode.loop)` to play the audio in loop.

**Comment by Ujas-Majithiya** [comment]
@AimanKyo97  you can to listen to player state changes using 
`playerController.onPlayerStateChanged.listen((state){});` stream which will provide any state changes in PlayerController. And as Dhaval said you can loop the player with `FinishMode.loop` enum. You will find this in the latest release. For more info check their documentation

**Comment by ujas-m-simformsolutions** [comment]
Closing this as we have this feature available now.
