### ISSUE TITLE
bug while release android 

### ISSUE THREAD

**Issue by hatemragab** [SimformSolutionsPvtLtd/audio_waveforms#71]
how to solve  iam try to use the 

```
  audio_waveforms:
    git: https://github.com/SimformSolutionsPvtLtd/audio_waveforms.git
```
and also v 0.1.3

``` gradle
* What went wrong:
Execution failed for task ':audio_waveforms:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/hatemragap/.gradle/caches/transforms-3/a9f4480d4badf2df91e3401ac7ead06e/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

```

**Comment by DhavalRKansara** [comment]
@hatemragab I have tried to run the example with version 0.1.3 on release mode in android and it's working fine on my end. Can you please share some steps to reproduce the issue and device info(Phone model, Android os and etc...) in which you are facing this? It will be helpful to us to find and fix the same.

**Comment by hatemragab** [comment]
@DhavalRKansara 
I have created a test project add just added the package to it then run flutter build apk 
and same error happened 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audio_waveforms:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/hatemragap/.gradle/caches/transforms-3/5e083c06c9925c2309f02468fc66e376/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```
test project url is [https://github.com/hatemragab/test_audio_wave](urltest_audio_wave)

**Comment by DhavalRKansara** [comment]
@hatemragab  Thanks for the response and sharing the repository we are able to replicate the same. There is one PR open for the same we need a minor change in it and requested the author for the same. We will wait for 2 days if He update else we will do the changes and release the updated version by Monday.
