### ISSUE TITLE
Duration doesn't reset after calling stop (IOS)

### ISSUE THREAD

**Issue by Flajt** [SimformSolutionsPvtLtd/audio_waveforms#74]
Hello, first of all thank you for this great package.

If I call `recoderController.stop()` and try to take a new recording without leaving the page (and triggering `dispose`), it will start by first displaying no wave. If one has the duration markers enabled, one can see that it renders the last timestamp at the near the left most position. 

<details><summary>Video of the issue</summary>

https://user-images.githubusercontent.com/25278830/182030798-27512974-ede1-4a2e-aa6b-f3b96d93f893.mp4

</details>

Device: Iphone 12 mini
IOS version: 15.6
Flutter Version: 3.0.4
package version: 0.1.3

Edit: No clue if the issue also is on android

Code snippet for my recording button:

```
class RecordingButton extends StatefulWidget {
  const RecordingButton(
      {Key? key, required this.controller, required this.audioManager})
      : super(key: key);
  final RecorderController controller;
  final AudioManager audioManager;
  @override
  _RecordingButtonState createState() => _RecordingButtonState();
}

class _RecordingButtonState extends State<RecordingButton> {
  bool isRecording = false;
  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
        onPressed: () async {
          isRecording = !isRecording;
          String savePath = await widget.audioManager.audioPath;
          isRecording == true
              ? await widget.controller.record(savePath)
              : await widget.controller.stop(true);
          setState(() {});
        },
        child: isRecording ? const Icon(Icons.stop) : const Icon(Icons.mic));
  }
}
```

**Comment by Ujas-Majithiya** [comment]
@Flajt Ok so what is happening here is, when you start recording the audio for second time it clears all the waves but it is not resetting the distance it pushed the first wave back and for new recording its starting from old distance.

Thanks for reporting this issue, we will soon release a fix

**Comment by Ujas-Majithiya** [comment]
@Flajt I have create a PR for the issue. You may use that branch until the next release

**Comment by Flajt** [comment]
I appreciate it. Thanks a lot.

**Comment by Ujas-Majithiya** [comment]
@Flajt and everyone, if you decide to set `callReset` to false you will manually require calling `reset()` from RecorderController to clear waves when recording again
