### ISSUE TITLE
AudioFileWaveforms does not show waveforms

### ISSUE THREAD

**Issue by captain-woof** [SimformSolutionsPvtLtd/audio_waveforms#77]
I'm using the `AudioFileWaveforms` in a row to create a player UI, and this is how I do it:

```dart
Container(
          margin: const EdgeInsets.symmetric(horizontal: 0, vertical: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              // Wave
              Expanded(
                child: LayoutBuilder(
                  builder: (context, constraints) => AudioFileWaveforms(
                    size: Size(constraints.maxWidth, 80.0),
                    playerController: _playerController,
                  ),
                ),
              ),

              // Timer
              const SizedBox(width: 4),
              Text(
                "${timeCounter.formattedTime}/${TimeCounter.formatTime(_trackDurationMillis)}",
                style: Theme.of(context).textTheme.bodySmall,
              ),
              const SizedBox(width: 4),

              // Pause/resume button (shown only when playing has started)
              IconButton(
                icon: Icon(
                    _audioPlayerState == AudioPlayerState.paused
                        ? Icons.play_arrow
                        : Icons.pause,
                    color: Colors.black),
                onPressed: _audioPlayerState != AudioPlayerState.stopped
                    ? () {
                        togglePauseResume(timeCounter);
                      }
                    : null,
              ),

              // Start/stop button (shown always)
              IconButton(
                icon: Icon(
                    (_audioPlayerState == AudioPlayerState.stopped ||
                            _audioPlayerState == AudioPlayerState.unprepared)
                        ? Icons.play_arrow
                        : Icons.stop,
                    color: Colors.red),
                onPressed: () {
                  toggleStartStop(timeCounter);
                },
              ),
            ],
          ),
        );
```

Thing is, it gets played correctly, but no waveforms appear. It's just blank. Why is this so?

**Comment by a1erons** [comment]
Same issues here

**Comment by Ujas-Majithiya** [comment]
@captain-woof Can you please share how you are preparing the player

**Comment by captain-woof** [comment]
@Ujas-Majithiya I had followed the docs in the first place.

I prepared the player, then set it to play. Like I said, the sound is heard alright, but the waves aren't there.

**Comment by Ujas-Majithiya** [comment]
@captain-woof This happens because you're showing the waveform widget before it had time to read the file and when it will try to calculate waveforms it will have no data calculate waveforms.

 So just add a condition above the waveform widget `playerController.playerState != PlayerState.stopped` and it will automatically show the widget and waveforms inside when it completes reading and calculation of waveform. Also, until then you can show a loading widget.

`PlayerState` is the current state of that player. You can also listen any changes in PlayerState using `onPlayerStateChanged`.

**Comment by captain-woof** [comment]
@Ujas-Majithiya Oh. Got it.

This should be mentioned in the docs. I thought preparing the player would then cause the Audio waveform widget to prepare as well. I didn't know it would start preparing right away.
