### ISSUE TITLE
Not showing waveforms 

### ISSUE THREAD

**Issue by a1erons** [SimformSolutionsPvtLtd/audio_waveforms#78]
This is not showing waveforms at all

**Comment by Ujas-Majithiya** [comment]
@a1erons  Can you please share some code of your implementation so that we can determine where is issue?

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue as no additional info was provided.

**Comment by a1erons** [comment]
Later got this resolved, the controllers **must be ready** and properly **initialized** before adding them to the audio waves widget!
Thanks
