### ISSUE TITLE
播放控制器停止后不能再次播放

### ISSUE THREAD

**Issue by mstestlp** [SimformSolutionsPvtLtd/audio_waveforms#83]
停止后状态是stop,不能播放了?
![image](https://user-images.githubusercontent.com/10651998/185288610-06aec9af-82da-464a-a196-952ac912f8a5.png)

**Comment by ujas-m-simformsolutions** [comment]
@mstestlp this happens because the default value of finishMode is `stop`.  You can check [here](https://pub.dev/documentation/audio_waveforms/latest/audio_waveforms/FinishMode.html) for more info.

**Comment by ujas-m-simformsolutions** [comment]
Closing this issue as no further info was provided, feel free to create a new issue
