### ISSUE TITLE
Player Reset Option

### ISSUE THREAD

**Issue by rlee1990** [SimformSolutionsPvtLtd/audio_waveforms#85]
I don't see an option to reset the player at all. Looping doesn't seem like a great option when using in a chat app.

**Comment by ujas-m-simformsolutions** [comment]
Hey @rlee1990, you can use `FinishMode.pause` and `FinishMode.stop`. If this option doesn't satisfy your use case, can you please share your use case or any suggestions?

**Comment by rlee1990** [comment]
@ujas-m-simformsolutions What I am trying to do is when the audio is done playing have the player reset the audio back to the start and have it ready to be played again. Putting it on stop doesn't allow us to play it again. Looping will still keep playing.

**Comment by ujas-m-simformsolutions** [comment]
@rlee1990 You can use `FinishMode.pause` for this use case

**Comment by rlee1990** [comment]
@ujas-m-simformsolutions No I can not that will just pause the file at the end and the person won't be able to hear it again from the start without closing the chat

**Comment by ujas-m-simformsolutions** [comment]
@rlee1990 With `FinishMode.pause` player will be paused at the end of the file but if you call `startPlayer` again it will start playing again from the start of the file. And if you are still facing this issue then please share your implementation so that we can check where is the issue.

**Comment by ujas-m-simformsolutions** [comment]
Closing this since no more feature info was provided and the current implementation works for the use case.
